Repository SpecterOps/BloodHound, pull requests merged in 2024-06, with the labels that each got.

#642 chore: update dependencies to mitigate vulnerabilities
  cmd/api/src/go.mod
  cmd/api/src/go.sum
Labels: api, ticketed

#644 chore: update dependencies to mitigate vulnerabilities
  .yarn/cache/tar-npm-6.1.15-44c3e71720-f23832fcee.zip
  .yarn/cache/tar-npm-6.2.1-237800bb20-f1322768c9.zip
  cmd/api/src/go.mod
  cmd/api/src/go.sum
  packages/go/cypher/go.mod
  packages/go/cypher/go.sum
  packages/go/schemagen/go.mod
  packages/go/schemagen/go.sum
  yarn.lock
Labels: api, user interface

#646 docs: fix certify and rubeus commands
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC1/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC13/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC3/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC4/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC6a/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC6b/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/WindowsAbuse.tsx
Labels: documentation

#650 docs: windows installation note
  README.md
Labels: documentation

#578 chore: modify dockerfile to build with stbernard
  .github/workflows/edge-publish.yml
  dockerfiles/bloodhound.Dockerfile
  packages/go/stbernard/command/builder/builder.go
  packages/go/stbernard/command/command.go
  packages/go/stbernard/environment/environment.go
  packages/go/stbernard/main.go
  packages/go/stbernard/workspace/golang/build.go
Labels: tooling

#660 Update pr-jira-issue-transfer.yml
  .github/workflows/pr-jira-issue-transfer.yml
Labels: bug, infrastructure, tooling

#662 add endpoints for fedramp eula
  packages/javascript/js-client-library/src/client.ts
Labels: enhancement, user interface

#664 BED-4485
  cmd/api/src/model/audit_test.go
  cmd/api/src/test/integration/harnesses/synclapspassword.svg
Labels: api

#669 chore: added more base schemas to new openapi docs
  packages/go/openapi/src/schemas/api.request.user.set-secret.yaml
  packages/go/openapi/src/schemas/api.request.user.update.yaml
  packages/go/openapi/src/schemas/api.response.pagination.yaml
  packages/go/openapi/src/schemas/api.response.time-window.yaml
  packages/go/openapi/src/schemas/enum.audit-log-status.yaml
  packages/go/openapi/src/schemas/enum.client-type.yaml
  packages/go/openapi/src/schemas/enum.datapipe-status.yaml
  packages/go/openapi/src/schemas/enum.job-status.yaml
  packages/go/openapi/src/schemas/enum.mfa-activation-status.yaml
  packages/go/openapi/src/schemas/enum.risk-acceptance.yaml
  packages/go/openapi/src/schemas/null.int32.yaml
  packages/go/openapi/src/schemas/null.int64.yaml
  packages/go/openapi/src/schemas/null.string.yaml
  packages/go/openapi/src/schemas/null.time.yaml
  packages/go/openapi/src/schemas/null.uuid.yaml
Labels: documentation

#673 chore: updated the github pull request template
  .github/pull_request_template.md
Labels: documentation

#670 chore: move type to api client
  cmd/ui/src/ducks/global/types.ts
  packages/javascript/js-client-library/src/client.ts
  packages/javascript/js-client-library/src/responses.ts
Labels: user interface

#676 BED-4391: Make v5.12.0 migration idempotent
  cmd/api/src/database/migration/migrations/v5.12.0.sql
Labels: bug, api

#671 BED-4488 (round 2) - Code cleanup and additional UX improvements on helper texts
  cmd/ui/src/views/DatabaseManagement/DatabaseManagement.test.tsx
  cmd/ui/src/views/DatabaseManagement/DatabaseManagement.tsx
  cmd/ui/src/views/DownloadCollectors/DownloadCollectors.tsx
  cmd/ui/src/views/EarlyAccessFeatures/EarlyAccessFeatures.tsx
  cmd/ui/src/views/QA/QA.tsx
  cmd/ui/src/views/SAMLConfiguration/SAMLConfiguration.tsx
  cmd/ui/src/views/Users/Users.tsx
  packages/javascript/bh-shared-ui/src/components/ContentPage/ContentPage.test.tsx
  packages/javascript/bh-shared-ui/src/components/ContentPage/ContentPage.tsx
  packages/javascript/bh-shared-ui/src/components/ContentPage/index.ts
  packages/javascript/bh-shared-ui/src/components/DocumentationLinks.tsx
  packages/javascript/bh-shared-ui/src/components/FileIngest/FileIngest.tsx
  packages/javascript/bh-shared-ui/src/components/PageWithTitle.tsx
  packages/javascript/bh-shared-ui/src/components/index.ts
  packages/javascript/bh-shared-ui/src/views/ApiExplorer/swagger/OperationsLayoutPlugin.tsx
  packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.tsx
Labels: user interface

#675 Bed 4489 accordion content
  packages/javascript/bh-shared-ui/src/components/MenuItem.tsx
Labels: user interface

#667 fix: missing name property on azure apps spawned by service principals
  cmd/api/src/api/bloodhoundgraph/conversions.go
  cmd/api/src/api/bloodhoundgraph/properties.go
  cmd/api/src/queries/graph.go
  packages/go/dawgs/graph/properties.go
  packages/go/dawgs/graph/properties_test.go
Labels: bug, api

#679 Supports 4489: add ISO_8601 date format
  packages/javascript/bh-shared-ui/src/utils/datetime.ts
Labels: user interface
