Repository SpecterOps/BloodHound, pull requests merged in 2024-09, with the labels that each got.

#825 BED-4746: button alignment on early access page
  cmd/ui/src/views/EarlyAccessFeatures/EarlyAccessFeatures.tsx
Labels: bug, user interface

#835 fix: schema inserts manually providing ids
  cmd/api/src/database/migration/migrations/schema.sql
Labels: api

#834 bump hound versions for RC
  dockerfiles/bloodhound.Dockerfile
  tools/docker-compose/api.Dockerfile
Labels: api

#837 chore: add license to file
  parca.yaml
Labels: api

#829 BED-4775 fixed multiple predicate SQL building error.
  cmd/api/src/database/agi.go
  cmd/api/src/database/audit.go
  cmd/api/src/database/auth.go
  cmd/api/src/database/file_upload.go
  cmd/api/src/database/saved_queries.go
  cmd/api/src/model/saved_queries_test.go
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
  parca.yaml
Labels: bug, api

#839 BED-4776: Add .github/CODEOWNERS
  .github/CODEOWNERS
Labels: tooling

#836 BED-4789 switch air from comstrek repo to air-verse
  tools/docker-compose/api.Dockerfile
Labels: infrastructure

#841 refactor: adcs cache with RWMutex
  cmd/api/src/analysis/ad/adcs_integration_test.go
  packages/go/analysis/ad/adcs.go
  packages/go/analysis/ad/adcscache.go
  packages/go/analysis/ad/esc1.go
  packages/go/analysis/ad/esc10.go
  packages/go/analysis/ad/esc13.go
  packages/go/analysis/ad/esc3.go
  packages/go/analysis/ad/esc4.go
  packages/go/analysis/ad/esc6.go
  packages/go/analysis/ad/esc9.go
Labels: bug, api

#810 fix: filter node property at ingest and for entity panel display
  cmd/api/src/daemons/datapipe/ingest.go
  cmd/api/src/daemons/datapipe/ingest_test.go
  packages/javascript/bh-shared-ui/src/views/Explore/fragments.test.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/fragments.tsx
Labels: api, user interface

#831 BP-881: Update README.md to reflect the docker-compose.yml filename change, which breaks the hyperlink
  README.md
Labels: ticketed

#812 fixed incorrect usage of readonly properties with model refs
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/schemas/model.audit-log.yaml
  packages/go/openapi/src/schemas/model.auth-token.yaml
  packages/go/openapi/src/schemas/model.client-scheduled-job.yaml
  packages/go/openapi/src/schemas/model.client.yaml
  packages/go/openapi/src/schemas/model.components.timestamps.yaml
  packages/go/openapi/src/schemas/model.user.yaml
Labels: documentation, api, tooling

#830 BED-4676 feat: Add support for prune TTLs and move reconciliation feature flag to parameters
  cmd/api/src/api/v2/app_config.go
  cmd/api/src/api/v2/app_config_integration_test.go
  cmd/api/src/api/v2/app_config_test.go
  cmd/api/src/api/v2/auth/auth.go
  cmd/api/src/bootstrap/server.go
  cmd/api/src/database/featureflags.go
  cmd/api/src/database/migration/migrations/v5.16.0.sql
  cmd/api/src/database/parameters.go
  cmd/api/src/database/parameters_test.go
  cmd/api/src/model/appcfg/flag.go
  cmd/api/src/model/appcfg/parameter.go
  cmd/api/src/model/appcfg/parameter_test.go
  cmd/api/src/model/audit.go
  cmd/api/src/utils/validation/duration_validator.go
  cmd/api/src/utils/validation/duration_validator_test.go
  cmd/api/src/utils/validation/mocks/validator.go
  cmd/api/src/utils/validation/password_validator.go
  cmd/api/src/utils/validation/password_validator_test.go
  cmd/api/src/utils/validation/registry.go
  cmd/api/src/utils/validation/required_validator.go
  cmd/api/src/utils/validation/required_validator_test.go
  cmd/api/src/utils/validation/validator.go
Labels: api

#858 BED-4835 Add SavedQueriesRead Permission To ReadOnly Role
  cmd/api/src/auth/role.go
  cmd/api/src/database/migration/migrations/v5.16.0.sql
Labels: bug, api

#860 BED-4128: Fix skip for audit endpoint
  cmd/api/src/api/v2/audit.go
  cmd/api/src/api/v2/audit_test.go
  cmd/api/src/api/v2/helpers.go
  cmd/api/src/model/pagination.go
Labels: bug

#854 BED-4388: Properly handle paths passed to OrphanFileSweeper
  cmd/api/src/daemons/datapipe/cleanup.go
  cmd/api/src/daemons/datapipe/cleanup_test.go
Labels: bug, api

#826 BED-4594+BED-4686: Styling fixes for `ExploreSearch` and `GraphButtons` components on the Explore page
  cmd/ui/src/components/GraphButtons/GraphButtons.test.tsx
  cmd/ui/src/components/GraphButtons/GraphButtons.tsx
  cmd/ui/src/components/GraphEvents.tsx
  cmd/ui/src/components/SigmaChart.tsx
  cmd/ui/src/styles/general.scss
  cmd/ui/src/views/Explore/ExploreSearch/CommonSearches.tsx
  cmd/ui/src/views/Explore/ExploreSearch/CypherSearch.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx
  cmd/ui/src/views/Explore/GraphView.tsx
  cmd/ui/src/views/Explore/utils.ts
  packages/javascript/bh-shared-ui/src/components/PrebuiltSearchList/PersonalSearchList.tsx
  packages/javascript/bh-shared-ui/src/components/PrebuiltSearchList/PrebuiltSearchList.tsx
  packages/javascript/bh-shared-ui/src/utils/exportGraphData.ts
Labels: bug, user interface

#867 BED-4696 feat: add preMigrationDaemons support
  cmd/api/src/bootstrap/initializer.go
  cmd/api/src/cmd/bhapi/main.go
  cmd/api/src/daemons/api/toolapi/api.go
  cmd/api/src/services/entrypoint.go
Labels: api

#828 SchannelAuthenticationEnabled
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/test/integration/graph.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/ESC10aHarnessDC1.json
  cmd/api/src/test/integration/harnesses/ESC10aHarnessDC1.svg
  cmd/api/src/test/integration/harnesses/ESC10aHarnessDC2.json
  cmd/api/src/test/integration/harnesses/ESC10aHarnessDC2.svg
  cmd/api/src/test/integration/harnesses/ESC10bHarnessDC1.json
  cmd/api/src/test/integration/harnesses/ESC10bHarnessDC1.svg
  cmd/api/src/test/integration/harnesses/ESC10bHarnessDC2.json
  cmd/api/src/test/integration/harnesses/ESC10bHarnessDC2.svg
  cmd/api/src/test/integration/harnesses/ESC6bHarnessDC1.json
  cmd/api/src/test/integration/harnesses/ESC6bHarnessDC1.svg
  cmd/api/src/test/integration/harnesses/ESC6bHarnessDC2.json
  cmd/api/src/test/integration/harnesses/ESC6bHarnessDC2.svg
  cmd/api/src/test/integration/harnesses/esc10aharness1.json
  cmd/api/src/test/integration/harnesses/esc10aharness1.svg
  cmd/api/src/test/integration/harnesses/esc10aharness2.json
  cmd/api/src/test/integration/harnesses/esc10aharness2.svg
  cmd/api/src/test/integration/harnesses/esc10aharnesseca.json
  cmd/api/src/test/integration/harnesses/esc10aharnesseca.svg
  cmd/api/src/test/integration/harnesses/esc10aharnessvictim.json
  cmd/api/src/test/integration/harnesses/esc10aharnessvictim.svg
  cmd/api/src/test/integration/harnesses/esc10aprincipalharness.json
  cmd/api/src/test/integration/harnesses/esc10aprincipalharness.svg
  cmd/api/src/test/integration/harnesses/esc10bharness1.json
  cmd/api/src/test/integration/harnesses/esc10bharness1.svg
  cmd/api/src/test/integration/harnesses/esc10bharness2.json
  cmd/api/src/test/integration/harnesses/esc10bharness2.svg
  cmd/api/src/test/integration/harnesses/esc10bharnesseca.json
  cmd/api/src/test/integration/harnesses/esc10bharnesseca.svg
  cmd/api/src/test/integration/harnesses/esc10bharnessvictim.json
  cmd/api/src/test/integration/harnesses/esc10bharnessvictim.svg
  cmd/api/src/test/integration/harnesses/esc10bprincipalharness.json
  cmd/api/src/test/integration/harnesses/esc10bprincipalharness.svg
  cmd/api/src/test/integration/harnesses/esc6b-eca.json
  cmd/api/src/test/integration/harnesses/esc6b-eca.svg
  cmd/api/src/test/integration/harnesses/esc6b-principal-edges.json
  cmd/api/src/test/integration/harnesses/esc6b-principal-edges.svg
  cmd/api/src/test/integration/harnesses/esc6b-template-1.json
  cmd/api/src/test/integration/harnesses/esc6b-template-1.svg
  cmd/api/src/test/integration/harnesses/esc6b-template-2.json
  cmd/api/src/test/integration/harnesses/esc6b-template-2.svg
  cmd/api/src/test/integration/harnesses/harnessgen.py
  packages/cue/bh/ad/ad.cue
  packages/go/analysis/ad/esc10.go
  packages/go/analysis/ad/esc6.go
  packages/go/analysis/ad/esc_shared.go
  packages/go/dawgs/query/model.go
  packages/go/graphschema/ad/ad.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: enhancement, external

#845 esc9b and esc10b abuse info improvement
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10a/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10b/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10b/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC4/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC9a/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC9b/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC9b/WindowsAbuse.tsx
Labels: enhancement, external

#872 BED-4863: Fix interpretation of no strongcertbinding reg value
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/ESC9aHarnessDC1.json
  cmd/api/src/test/integration/harnesses/ESC9aHarnessDC1.svg
  cmd/api/src/test/integration/harnesses/ESC9bHarnessDC1.json
  cmd/api/src/test/integration/harnesses/ESC9bHarnessDC1.svg
  packages/go/analysis/ad/adcscache.go
Labels: bug, external

#857 BED-3990: Missing group shortcutting
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/analysis/post_integration_test.go
  cmd/api/src/test/integration/graph.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/ESC9aHarnessAuthUsers.json
  cmd/api/src/test/integration/harnesses/ESC9aHarnessAuthUsers.svg
  cmd/api/src/test/integration/harnesses/ShortcutHarness.json
  cmd/api/src/test/integration/harnesses/ShortcutHarness.svg
  cmd/api/src/test/integration/harnesses/ShortcutHarnessAuthUsers.json
  cmd/api/src/test/integration/harnesses/ShortcutHarnessAuthUsers.svg
  cmd/api/src/test/integration/harnesses/ShortcutHarnessEveryone.json
  cmd/api/src/test/integration/harnesses/ShortcutHarnessEveryone.svg
  cmd/api/src/test/integration/harnesses/ShortcutHarnessEveryone2.json
  cmd/api/src/test/integration/harnesses/ShortcutHarnessEveryone2.svg
  cmd/api/src/test/integration/harnesses/adcsesc1-authusers.json
  cmd/api/src/test/integration/harnesses/adcsesc1-authusers.svg
  packages/go/analysis/ad/CalculateCrossProductNodeSetsDoc.md
  packages/go/analysis/ad/ad.go
  packages/go/analysis/ad/adcs.go
  packages/go/analysis/ad/adcscache.go
  packages/go/analysis/ad/esc1.go
  packages/go/analysis/ad/esc10.go
  packages/go/analysis/ad/esc13.go
  packages/go/analysis/ad/esc3.go
  packages/go/analysis/ad/esc4.go
  packages/go/analysis/ad/esc6.go
  packages/go/analysis/ad/esc9.go
  packages/go/analysis/ad/esc_shared.go
  packages/go/analysis/ad/post.go
  packages/go/analysis/ad/queries.go
Labels: enhancement, external

#840 Add abuse info for generic ACL edges against ADCS nodes
  packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Enroll/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Enroll/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Enroll/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/WindowsAbuse.tsx
Labels: enhancement, external

#875 BED-4853: Added feature flag for OIDC initiative
  cmd/api/src/database/migration/migrations/v6.0.0.sql
  cmd/api/src/model/appcfg/flag.go
Labels: release blocker

#878 Bed 4681: Added portal container getter export, upped doodle ui version
  .yarn/cache/@bloodhoundenterprise-doodleui-npm-1.0.0-alpha.5-e3bf9a2bcb-699c35f64e.zip
  .yarn/cache/@bloodhoundenterprise-doodleui-npm-1.0.0-alpha.6-93986f33ac-fb7673cd51.zip
  cmd/ui/package.json
  packages/javascript/bh-shared-ui/package.json
  packages/javascript/bh-shared-ui/src/constants.ts
  yarn.lock
Labels: user interface

#876 BED-4725: normalize files to UTF8 when extracting zip files for ingest
  cmd/api/src/daemons/datapipe/jobs.go
  cmd/api/src/services/fileupload/file_upload.go
Labels: bug, api

#883 BED-4871 added SchannelAuthenticationEnabled to cue file properties
  cmd/api/src/database/parameters_test.go
  cmd/api/src/model/appcfg/parameter_test.go
  cmd/api/src/test/integration/harnesses/ESC9aHarnessAuthUsers.svg
  cmd/api/src/test/integration/harnesses/ESC9aHarnessDC1.svg
  cmd/api/src/test/integration/harnesses/ESC9bHarnessDC1.svg
  cmd/api/src/test/integration/harnesses/ShortcutHarness.svg
  cmd/api/src/test/integration/harnesses/ShortcutHarnessAuthUsers.svg
  cmd/api/src/test/integration/harnesses/ShortcutHarnessEveryone.svg
  cmd/api/src/test/integration/harnesses/ShortcutHarnessEveryone2.svg
  cmd/api/src/test/integration/harnesses/adcsesc1-authusers.svg
  cmd/api/src/utils/validation/duration_validator.go
  cmd/api/src/utils/validation/duration_validator_test.go
  packages/cue/bh/ad/ad.cue
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
  packages/go/openapi/src/schemas/api.response.authenticated-requester.yaml
  packages/go/openapi/src/schemas/api.response.data-quality-platform-aggregate.yaml
  packages/go/openapi/src/schemas/api.response.finding.yaml
  packages/javascript/js-client-library/src/utils/config.ts
  packages/javascript/js-client-library/src/utils/index.ts
Labels: bug

#873 Bed 4752
  cmd/api/src/api/saml/saml.go
  cmd/api/src/api/v2/audit_test.go
  cmd/api/src/api/v2/helpers.go
  cmd/api/src/bootstrap/initializer.go
  cmd/api/src/cmd/bhapi/main.go
  cmd/api/src/daemons/datapipe/azure_convertors.go
  cmd/api/src/daemons/datapipe/jobs.go
  cmd/api/src/queries/graph.go
  packages/go/analysis/ad/adcs.go
  packages/go/analysis/ad/esc13.go
  packages/go/analysis/ad/esc3.go
  packages/go/analysis/azure/filters.go
  packages/go/analysis/azure/post.go
  packages/go/ein/azure.go
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
Labels: api

#884 BED-4753: Added styling selectors to address sections in api explorer not working in dark/light mode
  cmd/ui/src/App.tsx
Labels: bug, user interface

#889 BED-3945: More abuse info
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Contains/Abuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Contains/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/WindowsAbuse.tsx
Labels: documentation, external

#881 BED-4851 Create OIDC Provider Endpoint
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/v2/auth/oidc.go
  cmd/api/src/api/v2/auth/oidc_test.go
  cmd/api/src/database/db.go
  cmd/api/src/database/migration/migrations/v6.0.0.sql
  cmd/api/src/database/migration/migrations/v6.1.0.sql
  cmd/api/src/database/mocks/db.go
  cmd/api/src/database/oidc.go
  cmd/api/src/database/oidc_test.go
  cmd/api/src/model/oidc.go
  cmd/api/src/utils/validation/registry.go
  cmd/api/src/utils/validation/url_validator.go
  cmd/api/src/utils/validation/url_validator_test.go
Labels: api

#888 BED-4888: Cleaned up citrix RDP configuration tests
  packages/javascript/bh-shared-ui/src/components/CitrixRDPConfiguration/CitrixRDPConfiguration.test.tsx
Labels: user interface
