Repository SpecterOps/BloodHound, pull requests merged in 2024-07, with the labels that each got.

#665 BED-4435: Enforce AG name tag uniqueness
  cmd/api/src/api/error.go
  cmd/api/src/api/v2/agi.go
  cmd/api/src/api/v2/agi_test.go
  cmd/api/src/database/agi.go
  cmd/api/src/database/db.go
  cmd/api/src/database/migration/asset_group_constraints_test.go
  cmd/api/src/database/migration/migrations/v5.12.0.sql
Labels: api

#682 BED 4525: Fix broken link
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteSPN/References.tsx
Labels: documentation

#684 BED-4439: Broken collected filter
  cmd/api/src/model/filter.go
  cmd/api/src/model/search.go
Labels: api

#696 BED-4541: Add server version to profile page
  packages/javascript/bh-shared-ui/src/components/ApiVersion.tsx
  packages/javascript/bh-shared-ui/src/components/PageWithTitle.tsx
  packages/javascript/bh-shared-ui/src/components/index.ts
  packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.test.tsx
  packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.tsx
Labels: enhancement, user interface

#698 BED-4447: Hybrid Paths Small Tasks
  packages/javascript/bh-shared-ui/src/commonSearches.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/edgeTypes.tsx
Labels: enhancement, user interface

#701 feat: move dark mode behind feature flag
  cmd/api/src/model/appcfg/flag.go
  cmd/ui/src/components/SettingsMenu.tsx
  cmd/ui/src/store.ts
  cmd/ui/src/views/EarlyAccessFeatures/EarlyAccessFeatures.tsx
Labels: enhancement, api, user interface

#699 BED-4442 BED-4444 Hybrid Path edge panels
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/Opsec.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/SyncedToADUser.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/Opsec.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/SyncedToEntraUser.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
Labels: user interface

#702 BED-4549: Simple Entity Paths To OAPI Spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/aiacas.aiaca.id.controllers.yaml
  packages/go/openapi/src/paths/aiacas.aiaca.id.yaml
  packages/go/openapi/src/paths/certtemplate.certtemplates.id.controllers.yaml
  packages/go/openapi/src/paths/certtemplate.certtemplates.id.yaml
  packages/go/openapi/src/paths/containers.containers.id.controllers.yaml
  packages/go/openapi/src/paths/containers.containers.id.yaml
  packages/go/openapi/src/paths/enterprisecas.enterprisecas.id.controllers.yaml
  packages/go/openapi/src/paths/enterprisecas.enterprisecas.id.yaml
  packages/go/openapi/src/paths/eula.accept-eula.yaml
  packages/go/openapi/src/paths/ntauthstores.ntauthstores.id.controllers.yaml
  packages/go/openapi/src/paths/ntauthstores.ntauthstores.id.yaml
  packages/go/openapi/src/paths/rootcas.rootcas.id.controllers.yaml
  packages/go/openapi/src/paths/rootcas.rootcas.id.yaml
Labels: documentation, ticketed

#697 feat: use localstorage to persist dark mode setting
  cmd/api/src/database/migration/asset_group_constraints_test.go
  cmd/api/src/model/appcfg/flag.go
  cmd/ui/src/App.tsx
  cmd/ui/src/components/SettingsMenu.tsx
  cmd/ui/src/ducks/global/reducer.ts
  cmd/ui/src/ducks/global/types.ts
  cmd/ui/src/store.test.ts
  cmd/ui/src/store.ts
  cmd/ui/src/test-utils.jsx
  cmd/ui/src/views/EarlyAccessFeatures/EarlyAccessFeatures.tsx
  packages/javascript/bh-shared-ui/src/components/CreateSAMLProviderForm/CreateSAMLProviderForm.tsx
  packages/javascript/bh-shared-ui/src/test-utils.jsx
Labels: enhancement, user interface

#704 BED-4550: Add Computer Entity Paths to OAPI Spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/computers.computers.id.admin-rights.yaml
  packages/go/openapi/src/paths/computers.computers.id.admin-users.yaml
  packages/go/openapi/src/paths/computers.computers.id.constrained-delegation-rights.yaml
  packages/go/openapi/src/paths/computers.computers.id.constrained-users.yaml
  packages/go/openapi/src/paths/computers.computers.id.controllables.yaml
  packages/go/openapi/src/paths/computers.computers.id.controllers.yaml
  packages/go/openapi/src/paths/computers.computers.id.dcom-rights.yaml
  packages/go/openapi/src/paths/computers.computers.id.dcom-users.yaml
  packages/go/openapi/src/paths/computers.computers.id.group-membership.yaml
  packages/go/openapi/src/paths/computers.computers.id.ps-remote-rights.yaml
  packages/go/openapi/src/paths/computers.computers.id.ps-remote-users.yaml
  packages/go/openapi/src/paths/computers.computers.id.rdp-rights.yaml
  packages/go/openapi/src/paths/computers.computers.id.rdp-users.yaml
  packages/go/openapi/src/paths/computers.computers.id.sessions.yaml
  packages/go/openapi/src/paths/computers.computers.id.sql-admins.yaml
  packages/go/openapi/src/paths/computers.computers.id.yaml
  packages/go/openapi/src/paths/eula.accept-eula.yaml
Labels: documentation

#705 Bed 4556 add api info to oapi spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/api-info.spec.yaml
  packages/go/openapi/src/paths/api-info.version.yaml
  packages/go/openapi/src/paths/audit.audit.yaml
  packages/go/openapi/src/paths/config.config.yaml
  packages/go/openapi/src/paths/config.features.id.toggle.yaml
  packages/go/openapi/src/paths/config.features.yaml
  packages/go/openapi/src/schemas/model.app-config-param.yaml
  packages/go/openapi/src/schemas/model.audit-log.yaml
  packages/go/openapi/src/schemas/model.components.base-ad-entity.yaml
  packages/go/openapi/src/schemas/model.components.int32.id.yaml
  packages/go/openapi/src/schemas/model.components.int64.id.yaml
  packages/go/openapi/src/schemas/model.components.timestamps.yaml
  packages/go/openapi/src/schemas/model.components.uuid.yaml
  packages/go/openapi/src/schemas/model.feature-flag.yaml
Labels: documentation, api, tooling

#708 BED-4551: Add Domain Entity Paths to OAPI Spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/domains.domains.id.computers.yaml
  packages/go/openapi/src/paths/domains.domains.id.controllers.yaml
  packages/go/openapi/src/paths/domains.domains.id.dc-syncers.yaml
  packages/go/openapi/src/paths/domains.domains.id.foreign-admins.yaml
  packages/go/openapi/src/paths/domains.domains.id.foreign-gpo-controllers.yaml
  packages/go/openapi/src/paths/domains.domains.id.foreign-groups.yaml
  packages/go/openapi/src/paths/domains.domains.id.foreign-users.yaml
  packages/go/openapi/src/paths/domains.domains.id.gpos.yaml
  packages/go/openapi/src/paths/domains.domains.id.groups.yaml
  packages/go/openapi/src/paths/domains.domains.id.inbound-trusts.yaml
  packages/go/openapi/src/paths/domains.domains.id.linked-gpos.yaml
  packages/go/openapi/src/paths/domains.domains.id.ous.yaml
  packages/go/openapi/src/paths/domains.domains.id.outbound-trusts.yaml
  packages/go/openapi/src/paths/domains.domains.id.users.yaml
  packages/go/openapi/src/paths/domains.domains.id.yaml
Labels: documentation, api, tooling

#707 BED-4570: Resolve panics with IngestibleRelationship
  cmd/api/src/daemons/datapipe/convertors.go
  packages/go/ein/ad.go
  packages/go/ein/azure.go
  packages/go/ein/models.go
Labels: bug, api

#626 fix: compositions for multi-tier PKI
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/esc6a-template2.json
  cmd/api/src/test/integration/harnesses/esc6a-template2.png
  cmd/api/src/test/integration/harnesses/esc6b-template-2.json
  cmd/api/src/test/integration/harnesses/esc6b-template-2.png
  packages/go/analysis/ad/esc10.go
  packages/go/analysis/ad/esc3.go
  packages/go/analysis/ad/esc4.go
  packages/go/analysis/ad/esc6.go
  packages/go/analysis/ad/esc9.go
Labels: bug

#717 BED-4574: Dark Mode early access fix
  cmd/ui/src/App.tsx
Labels: bug, user interface

#630 fix: EnrollOnBehalfOf to be based on EffectiveEKUs
  cmd/api/src/test/integration/graph.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/enrollonbehalfof-1.json
  cmd/api/src/test/integration/harnesses/enrollonbehalfof-2.json
  cmd/api/src/test/integration/harnesses/harnessgen.py
  cmd/ui/src/ducks/entityinfo/types.ts
  packages/go/analysis/ad/esc3.go
Labels: bug

#661 BED-4366 -- parse negative numbers in Cypher queries
  packages/go/cypher/backend/cypher/format.go
  packages/go/cypher/frontend/expression.go
  packages/go/cypher/model/copy.go
  packages/go/cypher/model/model.go
  packages/go/cypher/model/walk.go
  packages/go/cypher/test/cases/positive_tests.json
Labels: bug, api

#713 BED-4553: Add User Entity Paths to OAPI Spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/users.users.id.admin-rights.yaml
  packages/go/openapi/src/paths/users.users.id.constrained-delegation-rights.yaml
  packages/go/openapi/src/paths/users.users.id.controllables.yaml
  packages/go/openapi/src/paths/users.users.id.controllers.yaml
  packages/go/openapi/src/paths/users.users.id.dcom-rights.yaml
  packages/go/openapi/src/paths/users.users.id.memberships.yaml
  packages/go/openapi/src/paths/users.users.id.ps-remote-rights.yaml
  packages/go/openapi/src/paths/users.users.id.rdp-rights.yaml
  packages/go/openapi/src/paths/users.users.id.sessions.yaml
  packages/go/openapi/src/paths/users.users.id.sql-admin-rights.yaml
  packages/go/openapi/src/paths/users.users.id.yaml
Labels: documentation, api, tooling

#719 BED-4554: Add Base Entity, Azure Entity, and Meta Entity Paths to OAPI Spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/azure.entity.yaml
  packages/go/openapi/src/paths/base.base.id.controllables.yaml
  packages/go/openapi/src/paths/base.base.id.controllers.yaml
  packages/go/openapi/src/paths/base.base.id.yaml
  packages/go/openapi/src/paths/meta-entity.meta.id.yaml
Labels: documentation, api, tooling

#723 fix: dark mode migration
  cmd/api/src/database/migration/migrations/v5.13.0.sql
  cmd/ui/public/img/logo-secondary-transparent-banner.svg
  cmd/ui/public/img/logo-secondary-transparent-full.svg
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/Opsec.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToADUser/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/Opsec.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/PageWithTitle.tsx
  packages/javascript/bh-shared-ui/src/utils/colors.ts
Labels: enhancement

#716 BED-4559: added grapher, cypher, and search endpoints to openapi spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/cypher.graphs.cypher.yaml
  packages/go/openapi/src/paths/cypher.saved-queries.id.yaml
  packages/go/openapi/src/paths/cypher.saved-queries.yaml
  packages/go/openapi/src/paths/graph.graph-search.yaml
  packages/go/openapi/src/paths/graph.graphs.edge-composition.yaml
  packages/go/openapi/src/paths/graph.graphs.shortest-path.yaml
  packages/go/openapi/src/paths/graph.pathfinding.yaml
  packages/go/openapi/src/paths/search.available-domains.yaml
  packages/go/openapi/src/paths/search.search.yaml
  packages/go/openapi/src/schemas/model.domain-selector.yaml
  packages/go/openapi/src/schemas/model.saved-query.yaml
  packages/go/openapi/src/schemas/model.search-result.yaml
  packages/go/openapi/src/schemas/model.unified-graph.edge.yaml
  packages/go/openapi/src/schemas/model.unified-graph.graph.yaml
  packages/go/openapi/src/schemas/model.unified-graph.node.yaml
Labels: documentation, api, tooling

#718 BED-4560: add data related endpoints to open api spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/data-quality.ad-domains.id.data-quality-stats.yaml
  packages/go/openapi/src/paths/data-quality.azure-tenants.id.data-quality-stats.yaml
  packages/go/openapi/src/paths/data-quality.clear-database.yaml
  packages/go/openapi/src/paths/data-quality.completeness.yaml
  packages/go/openapi/src/paths/data-quality.platform.id.data-quality-stats.yaml
  packages/go/openapi/src/paths/datapipe.analysis.yaml
  packages/go/openapi/src/paths/datapipe.datapipe.status.yaml
  packages/go/openapi/src/schemas/model.ad-data-quality-aggregation.yaml
  packages/go/openapi/src/schemas/model.ad-data-quality-stat.yaml
  packages/go/openapi/src/schemas/model.azure-data-quality-aggregation.yaml
  packages/go/openapi/src/schemas/model.azure-data-quality-stat.yaml
Labels: documentation, api, tooling

#720 BED-4555: added analysis related paths to openapi spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/analysis.asset-groups.id.combo-node.yaml
  packages/go/openapi/src/paths/analysis.meta-nodes.id.yaml
  packages/go/openapi/src/paths/analysis.meta-trees.id.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.collections.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.custom-selectors.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.members.counts.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.members.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.selectors.id.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.selectors.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-groups.yaml
  packages/go/openapi/src/paths/attack-paths.attack-path-types.yaml
  packages/go/openapi/src/paths/attack-paths.attack-paths.id.acceptance.yaml
  packages/go/openapi/src/paths/attack-paths.attack-paths.yaml
  packages/go/openapi/src/paths/attack-paths.domains.id.attack-path-findings.yaml
  packages/go/openapi/src/paths/attack-paths.domains.id.available-types.yaml
  packages/go/openapi/src/paths/attack-paths.domains.id.details.yaml
  packages/go/openapi/src/paths/attack-paths.domains.id.sparkline.yaml
  packages/go/openapi/src/paths/risk-posture.posture-stats.yaml
  packages/go/openapi/src/schemas/model.asset-group-collection-entry.yaml
  packages/go/openapi/src/schemas/model.asset-group-collection.yaml
  packages/go/openapi/src/schemas/model.asset-group-member.yaml
  packages/go/openapi/src/schemas/model.asset-group-selector-spec.yaml
  packages/go/openapi/src/schemas/model.asset-group-selector.yaml
  packages/go/openapi/src/schemas/model.asset-group.yaml
  packages/go/openapi/src/schemas/model.list-finding.yaml
  packages/go/openapi/src/schemas/model.relationship-finding.yaml
  packages/go/openapi/src/schemas/model.risk-counts.yaml
  packages/go/openapi/src/schemas/model.risk-posture-stat.yaml
Labels: documentation, api, tooling

#724 BED-4598: added group entities to open api spec
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/README.md
  packages/go/openapi/src/paths/groups.groups.id.admins-rights.yaml
  packages/go/openapi/src/paths/groups.groups.id.controllables.yaml
  packages/go/openapi/src/paths/groups.groups.id.controllers.yaml
  packages/go/openapi/src/paths/groups.groups.id.dcom-rights.yaml
  packages/go/openapi/src/paths/groups.groups.id.members.yaml
  packages/go/openapi/src/paths/groups.groups.id.memberships.yaml
  packages/go/openapi/src/paths/groups.groups.id.ps-remote-rights.yaml
  packages/go/openapi/src/paths/groups.groups.id.rdp-rights.yaml
  packages/go/openapi/src/paths/groups.groups.id.sessions.yaml
  packages/go/openapi/src/paths/groups.groups.id.yaml
  packages/go/openapi/src/schemas/api.request.user.set-secret.yaml
  packages/go/openapi/src/schemas/api.request.user.update.yaml
Labels: documentation, api, tooling

#727 Bed 4609
  cmd/api/src/api/v2/agi.go
  cmd/api/src/api/v2/agi_test.go
  cmd/api/src/api/v2/app_config_test.go
  cmd/api/src/api/v2/search_internal_test.go
  cmd/api/src/api/v2/search_test.go
  cmd/api/src/model/filter.go
  packages/javascript/bh-shared-ui/src/constants.ts
Labels: api

#731 BED-4589: Graph loading bar contrast in dark mode
  packages/javascript/bh-shared-ui/src/constants.ts
Labels: user interface

#734 BED-4592: Remove unnecessary highlighting from Search Current Nodes
  packages/javascript/bh-shared-ui/src/components/SearchCurrentNodes/SearchCurrentNodes.tsx
Labels: bug, user interface

#735 fix: filters active button styles
  packages/javascript/bh-shared-ui/src/components/AssetGroupFilters/AssetGroupFilters.test.tsx
  packages/javascript/bh-shared-ui/src/components/AssetGroupFilters/AssetGroupFilters.tsx
Labels: bug, user interface

#737 BED-4591: api-explorer filter input styles
  cmd/ui/src/App.tsx
Labels: bug, user interface

#736 fix: login button styles
  cmd/ui/src/components/LoginForm/LoginForm.tsx
  cmd/ui/src/components/LoginViaSAMLForm/LoginViaSAMLForm.tsx
  cmd/ui/src/views/DisabledUser.tsx
Labels: bug, user interface

#728 BED-4168: Fixed inaccurate AG member_count value
  cmd/api/src/database/agi.go
  cmd/api/src/database/agi_test.go
  packages/go/errors/error.go
Labels: api

#738 BED-4627: global scrollbar styles
  cmd/ui/src/styles/general.scss
  packages/javascript/bh-shared-ui/src/views/Explore/InfoStyles/Pane.tsx
Labels: user interface

#740 BED 4628: Error alert text contrast
  packages/javascript/bh-shared-ui/src/constants.ts
Labels: bug, user interface

#742 fix: theme graph label colors
  cmd/ui/src/rendering/programs/edge-label.ts
  cmd/ui/src/rendering/programs/node-hover.ts
  cmd/ui/src/rendering/programs/node-label.ts
  cmd/ui/src/rendering/utils/utils.ts
  cmd/ui/src/utils.ts
  cmd/ui/src/views/Explore/GraphView.tsx
  cmd/ui/src/views/Explore/utils.ts
  packages/javascript/bh-shared-ui/src/utils/icons.ts
Labels: bug, user interface

#726 fix: misc. updates to styles
  cmd/ui/src/App.tsx
  cmd/ui/src/components/LoginForm/LoginForm.tsx
  cmd/ui/src/components/LoginViaSAMLForm/LoginViaSAMLForm.tsx
  cmd/ui/src/rendering/programs/edge-label.ts
  cmd/ui/src/rendering/programs/node-hover.ts
  cmd/ui/src/rendering/programs/node-label.ts
  cmd/ui/src/rendering/utils/utils.ts
  cmd/ui/src/styles/general.scss
  cmd/ui/src/utils.ts
  cmd/ui/src/views/DisabledUser.tsx
  cmd/ui/src/views/Explore/ExploreSearch/CypherSearch.tsx
  cmd/ui/src/views/Explore/GraphView.tsx
  cmd/ui/src/views/Explore/utils.ts
  packages/javascript/bh-shared-ui/src/components/AssetGroupEdit/AssetGroupEdit.tsx
  packages/javascript/bh-shared-ui/src/components/AssetGroupFilters/AssetGroupFilters.test.tsx
  packages/javascript/bh-shared-ui/src/components/AssetGroupFilters/AssetGroupFilters.tsx
  packages/javascript/bh-shared-ui/src/components/AssetGroupMemberList/AssetGroupMemberList.tsx
  packages/javascript/bh-shared-ui/src/components/GroupManagementContent/GroupManagementContent.tsx
  packages/javascript/bh-shared-ui/src/components/SearchCurrentNodes/SearchCurrentNodes.tsx
  packages/javascript/bh-shared-ui/src/constants.ts
  packages/javascript/bh-shared-ui/src/utils/icons.ts
  packages/javascript/bh-shared-ui/src/views/Explore/InfoStyles/Pane.tsx
Labels: bug, user interface

#739 Bed 4569 finalize openapi spec pt2
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/v2/docs.go
  cmd/api/src/cmd/bhapi/main.go
  cmd/api/src/docs/docs.go
  cmd/api/src/docs/json/definitions/api.json
  cmd/api/src/docs/json/definitions/attributes.json
  cmd/api/src/docs/json/definitions/definitions.json
  cmd/api/src/docs/json/definitions/graphs.json
  cmd/api/src/docs/json/definitions/models.json
  cmd/api/src/docs/json/definitions/parameters.json
  cmd/api/src/docs/json/definitions/predicates.json
  cmd/api/src/docs/json/definitions/properties.json
  cmd/api/src/docs/json/definitions/v2.json
  cmd/api/src/docs/json/paths/v2/aiaca-entity.json
  cmd/api/src/docs/json/paths/v2/api-info.json
  cmd/api/src/docs/json/paths/v2/asset-isolation.json
  cmd/api/src/docs/json/paths/v2/attack-paths.json
  cmd/api/src/docs/json/paths/v2/audit.json
  cmd/api/src/docs/json/paths/v2/auth.json
  cmd/api/src/docs/json/paths/v2/azure.json
  cmd/api/src/docs/json/paths/v2/base-entity.json
  cmd/api/src/docs/json/paths/v2/certtemplate-entity.json
  cmd/api/src/docs/json/paths/v2/clear-database.json
  cmd/api/src/docs/json/paths/v2/clients.json
  cmd/api/src/docs/json/paths/v2/collectors.json
  cmd/api/src/docs/json/paths/v2/computer-entity.json
  cmd/api/src/docs/json/paths/v2/config.json
  cmd/api/src/docs/json/paths/v2/container-entity.json
  cmd/api/src/docs/json/paths/v2/data-quality-stats.json
  cmd/api/src/docs/json/paths/v2/datapipe.json
  cmd/api/src/docs/json/paths/v2/domain-entity.json
  cmd/api/src/docs/json/paths/v2/enterpriseca-entity.json
  cmd/api/src/docs/json/paths/v2/events.json
  cmd/api/src/docs/json/paths/v2/file_upload.json
  cmd/api/src/docs/json/paths/v2/gpo-entity.json
  cmd/api/src/docs/json/paths/v2/graph.json
  cmd/api/src/docs/json/paths/v2/graphs.json
  cmd/api/src/docs/json/paths/v2/group-entity.json
  cmd/api/src/docs/json/paths/v2/ingestion.json
  cmd/api/src/docs/json/paths/v2/issuancepolicy-entity.json
  cmd/api/src/docs/json/paths/v2/jobs.json
  cmd/api/src/docs/json/paths/v2/meta-entity.json
  cmd/api/src/docs/json/paths/v2/ntauthstore-entity.json
  cmd/api/src/docs/json/paths/v2/ou-entity.json
  cmd/api/src/docs/json/paths/v2/posture.json
  cmd/api/src/docs/json/paths/v2/qa.json
  cmd/api/src/docs/json/paths/v2/rootca-entity.json
  cmd/api/src/docs/json/paths/v2/saved_queries.json
  cmd/api/src/docs/json/paths/v2/search.json
  cmd/api/src/docs/json/paths/v2/tasks.json
  cmd/api/src/docs/json/paths/v2/user-entity.json
  cmd/api/src/go.mod
  cmd/api/src/go.sum
  packages/go/openapi/doc/openapi.json
  packages/javascript/bh-shared-ui/src/views/ApiExplorer/ApiExplorer.tsx
Labels: documentation, api, tooling

#744 Bed 4444: Fix windows abuse content
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SyncedToEntraUser/WindowsAbuse.tsx
Labels: bug, user interface

#745 fix: BED-4633 - fix incorrect usage of `allOf` in OpenAPI spec
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.members.yaml
  packages/go/openapi/src/paths/collection-uploads.file-upload.yaml
  packages/go/openapi/src/paths/cypher.saved-queries.yaml
  packages/go/openapi/src/schemas/model.ad-data-quality-aggregation.yaml
  packages/go/openapi/src/schemas/model.ad-data-quality-stat.yaml
  packages/go/openapi/src/schemas/model.app-config-param.yaml
  packages/go/openapi/src/schemas/model.asset-group-collection-entry.yaml
  packages/go/openapi/src/schemas/model.asset-group-collection.yaml
  packages/go/openapi/src/schemas/model.asset-group-selector.yaml
  packages/go/openapi/src/schemas/model.asset-group.yaml
  packages/go/openapi/src/schemas/model.audit-log.yaml
  packages/go/openapi/src/schemas/model.auth-secret.yaml
  packages/go/openapi/src/schemas/model.auth-token.yaml
  packages/go/openapi/src/schemas/model.azure-data-quality-aggregation.yaml
  packages/go/openapi/src/schemas/model.azure-data-quality-stat.yaml
  packages/go/openapi/src/schemas/model.bh-graph.edge.yaml
  packages/go/openapi/src/schemas/model.bh-graph.node.yaml
  packages/go/openapi/src/schemas/model.client-display.yaml
  packages/go/openapi/src/schemas/model.client-schedule-display.yaml
  packages/go/openapi/src/schemas/model.client-schedule.yaml
  packages/go/openapi/src/schemas/model.client-scheduled-job-display.yaml
  packages/go/openapi/src/schemas/model.client-scheduled-job.yaml
  packages/go/openapi/src/schemas/model.client.yaml
  packages/go/openapi/src/schemas/model.components.timestamps.yaml
  packages/go/openapi/src/schemas/model.domain-collection-result.yaml
  packages/go/openapi/src/schemas/model.domain-details.yaml
  packages/go/openapi/src/schemas/model.feature-flag.yaml
  packages/go/openapi/src/schemas/model.file-upload-job.yaml
  packages/go/openapi/src/schemas/model.list-finding.yaml
  packages/go/openapi/src/schemas/model.ou-details.yaml
  packages/go/openapi/src/schemas/model.permission.yaml
  packages/go/openapi/src/schemas/model.relationship-finding.yaml
  packages/go/openapi/src/schemas/model.risk-counts.yaml
  packages/go/openapi/src/schemas/model.risk-posture-stat.yaml
  packages/go/openapi/src/schemas/model.role.yaml
  packages/go/openapi/src/schemas/model.saml-provider.yaml
  packages/go/openapi/src/schemas/model.saved-query.yaml
  packages/go/openapi/src/schemas/model.user.yaml
Labels: documentation, api, tooling

#751 Bed 4638: table root remove bgimage
  packages/javascript/bh-shared-ui/src/constants.ts
Labels: bug, user interface

#747 chore: BED-4580 - add audit log failures to delete auth token
  cmd/api/src/api/v2/apiclient/auth.go
  cmd/api/src/api/v2/auth/auth.go
  cmd/api/src/api/v2/auth_integration_test.go
  cmd/api/src/api/v2/integration/auth.go
  cmd/api/src/database/auth.go
  cmd/api/src/database/auth_test.go
Labels: api

#750 BED-4639: Update Copy menu palette for dark mode
  cmd/ui/src/views/Explore/ContextMenu/CopyMenuItem.tsx
Labels: bug, user interface

#752 BED-4645: Update support link to point directly to docs
  cmd/ui/src/components/SettingsMenu.tsx
Labels: documentation

#754 chore: gpo abuse info
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GPLink/Abuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GPLink/GPLink.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GPLink/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GPLink/WindowsAbuse.tsx
Labels: documentation

#753 BED-4641 - Create Ingest Defect Graph Migration
  cmd/api/src/migrations/graph.go
  cmd/api/src/migrations/manifest.go
  packages/go/dawgs/drivers/neo4j/cypher.go
  packages/go/dawgs/ops/ops.go
  packages/go/dawgs/query/model.go
Labels: bug

#756 Update friendly name for blocksinheritance property
  cmd/api/src/test/integration/harnesses/enterprisecaforharness.svg
  cmd/api/src/test/integration/harnesses/issuedsignedbyharness.svg
  packages/cue/bh/ad/ad.cue
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/EnterpriseCAFor/General.tsx
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: user interface

#758 BED-4649: file drop color palette
  packages/javascript/bh-shared-ui/src/components/FileDrop/FileDrop.tsx
Labels: bug, user interface
