Repository SpecterOps/BloodHound, pull requests merged in 2024-05, with the labels that each got.

#580 feat: funnel localgroups and localusers through the Base entity endoint, enable obtaining object information even if type is not in schema
  cmd/ui/src/views/Explore/BasicObjectInfoFields.tsx
  cmd/ui/src/views/Explore/EdgeInfo/EdgeObjectInformation.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoContent.test.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoContent.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTableList.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoHeader.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoPanel.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityObjectInformation.tsx
  cmd/ui/src/views/Explore/utils.test.ts
  cmd/ui/src/views/Explore/utils.ts
  cmd/ui/src/views/GroupManagement/GroupManagement.test.tsx
  cmd/ui/src/views/GroupManagement/GroupManagement.tsx
  packages/javascript/bh-shared-ui/rollup.config.js
  packages/javascript/bh-shared-ui/src/constants.ts
  packages/javascript/bh-shared-ui/src/hooks/useSearch/useSearch.tsx
  packages/javascript/bh-shared-ui/src/index.ts
  packages/javascript/bh-shared-ui/src/utils/content.ts
  packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.test.ts
  packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.ts
  packages/javascript/bh-shared-ui/src/views/Explore/fragments.tsx
  packages/javascript/js-client-library/src/client.ts
Labels: bug, enhancement, user interface

#591 Update the AZUserAccessAdministrator help text
  packages/javascript/bh-shared-ui/src/components/HelpTexts/AZUserAccessAdministrator/Abuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/AZUserAccessAdministrator/General.tsx
Labels: triage

#599 BED-4358: Add Complexity Measurement For Graph Mutations
  cmd/api/src/api/v2/cypherquery_integration_test.go
  cmd/api/src/queries/graph_test.go
  packages/go/cypher/analyzer/analyzer.go
  packages/go/cypher/analyzer/analyzer_test.go
  packages/go/cypher/analyzer/measure.go
  packages/go/cypher/backend/cypher/format_test.go
  packages/go/cypher/frontend/query.go
  packages/go/cypher/test/cases.go
  packages/go/cypher/test/cases/mutation_tests.json
  packages/go/cypher/test/cases/negative_tests.json
  packages/go/cypher/test/cases/positive_tests.json
  packages/go/cypher/test/test.go
Labels: bug, enhancement, api

#603 feat: add parameter parsing support to cypher frontend
  packages/go/cypher/frontend/atom.go
  packages/go/cypher/frontend/expression.go
  packages/go/cypher/test/cases/positive_tests.json
Labels: enhancement

#567 Additional Organizational Units ACLs
  packages/cue/bh/ad/ad.cue
  packages/go/graphschema/ad/ad.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericWrite/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteGPLink/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteGPLink/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteGPLink/Opsec.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteGPLink/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteGPLink/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteGPLink/WriteGPLink.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
  packages/javascript/bh-shared-ui/src/graphSchema.ts
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/edgeTypes.tsx
Labels: enhancement, triage
