Repository SpecterOps/BloodHound, pull requests merged in 2024-04, with the labels that each got.

#532 Update UI images to use `node:20-alpine` as base image
  .github/workflows/static-code-analysis.yml
  .yarn/cache/@esbuild-darwin-arm64-npm-0.20.2-e287d70c91-8.zip
  .yarn/cache/@esbuild-darwin-x64-npm-0.20.2-f4f3a851d1-8.zip
  .yarn/cache/@esbuild-linux-arm64-npm-0.20.2-3a02a82580-8.zip
  .yarn/cache/@esbuild-win32-arm64-npm-0.20.2-f2a0280705-8.zip
  .yarn/cache/@esbuild-win32-x64-npm-0.20.2-4f45bbb49b-8.zip
  .yarn/cache/@rollup-rollup-darwin-arm64-npm-4.13.2-20c5519087-8.zip
  .yarn/cache/@rollup-rollup-darwin-x64-npm-4.13.2-d3f8841c56-8.zip
  .yarn/cache/@rollup-rollup-linux-arm64-gnu-npm-4.13.2-6e5b44140f-8.zip
  .yarn/cache/@rollup-rollup-win32-arm64-msvc-npm-4.13.2-75257194f5-8.zip
  .yarn/cache/@rollup-rollup-win32-x64-msvc-npm-4.13.2-4638a893f3-8.zip
  .yarn/cache/@types-node-npm-18.17.1-4d5cf864b8-56201bda9a.zip
  .yarn/cache/@types-node-npm-20.11.29-4e883af835-d6d37d4f72.zip
  .yarn/cache/@types-node-npm-20.4.5-7555fad0d4-36a0304a8d.zip
  .yarn/cache/fsevents-patch-21ad2b1333-8.zip
  .yarn/cache/undici-types-npm-5.26.5-de4f7c7bb9-3192ef6f3f.zip
  .yarnrc.yml
  DEVREADME.md
  cmd/ui/package.json
  dockerfiles/bloodhound.Dockerfile
  tools/docker-compose/ui.Dockerfile
  yarn.lock
Labels: user interface, tooling

#531 fix: add missing node types to data quality stats and display
  cmd/api/src/analysis/azure/queries.go
  cmd/api/src/database/migration/migrations/v5.8.1.sql
  cmd/api/src/model/azurequality.go
  cmd/ui/src/ducks/global/reducer.ts
  cmd/ui/src/ducks/global/types.ts
  packages/javascript/bh-shared-ui/src/components/NodeIcon/NodeIcon.tsx
  packages/javascript/bh-shared-ui/src/hooks/useDataQualityStats.tsx
  packages/javascript/bh-shared-ui/src/views/DataQuality/DomainInfo.tsx
  packages/javascript/bh-shared-ui/src/views/DataQuality/LoadContainer/LoadContainer.test.tsx
  packages/javascript/bh-shared-ui/src/views/DataQuality/LoadContainer/LoadContainer.tsx
  packages/javascript/bh-shared-ui/src/views/DataQuality/TenantInfo.tsx
  packages/javascript/js-client-library/src/client.ts
  packages/javascript/js-client-library/src/responses.ts
Labels: bug, api, user interface

#545 Revert "feat: post process AZAddSecret edges from roles instead of principals"
  cmd/api/src/analysis/azure/azure_integration_test.go
  cmd/api/src/analysis/azure/post.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/AZAddSecretHarness.json
  cmd/api/src/test/integration/harnesses/AZAddSecretHarness.svg
  packages/go/analysis/azure/post.go
  packages/go/analysis/azure/tenant.go
Labels: bug

#518 chore: BED-4141 - added parameters and supporting schemas to openapi src
  justfile
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/parameters/header.prefer.yaml
  packages/go/openapi/src/parameters/path.object-id.yaml
  packages/go/openapi/src/parameters/query.created-at.yaml
  packages/go/openapi/src/parameters/query.deleted-at.yaml
  packages/go/openapi/src/parameters/query.entity.limit.yaml
  packages/go/openapi/src/parameters/query.entity.skip.yaml
  packages/go/openapi/src/parameters/query.entity.sort-by.yaml
  packages/go/openapi/src/parameters/query.entity.type.yaml
  packages/go/openapi/src/parameters/query.hydrate-counts.yaml
  packages/go/openapi/src/parameters/query.limit.yaml
  packages/go/openapi/src/parameters/query.skip.yaml
  packages/go/openapi/src/parameters/query.updated-at.yaml
  packages/go/openapi/src/schemas/api.params.predicate.filter.boolean.yaml
  packages/go/openapi/src/schemas/api.params.predicate.filter.contains.yaml
  packages/go/openapi/src/schemas/api.params.predicate.filter.integer.yaml
  packages/go/openapi/src/schemas/api.params.predicate.filter.string.yaml
  packages/go/openapi/src/schemas/api.params.predicate.filter.time.yaml
  packages/go/openapi/src/schemas/api.params.predicate.filter.uuid.yaml
  packages/go/openapi/src/schemas/api.params.query.limit.yaml
  packages/go/openapi/src/schemas/api.params.query.skip.yaml
  packages/go/openapi/src/schemas/api.params.query.sort-by.yaml
Labels: documentation

#519 chore: BED-4141 - Added common responses to openapi spec src
  packages/go/openapi/src/responses/bad-request.yaml
  packages/go/openapi/src/responses/binary-response.yaml
  packages/go/openapi/src/responses/csv-response.yaml
  packages/go/openapi/src/responses/error-response.yaml
  packages/go/openapi/src/responses/forbidden.yaml
  packages/go/openapi/src/responses/internal-server-error.yaml
  packages/go/openapi/src/responses/no-content.yaml
  packages/go/openapi/src/responses/not-found.yaml
  packages/go/openapi/src/responses/too-many-requests.yaml
  packages/go/openapi/src/responses/unauthorized.yaml
  packages/go/openapi/src/schemas/api.error-detail.yaml
  packages/go/openapi/src/schemas/api.error-wrapper.yaml
Labels: documentation

#551 fix: update kinds slice in graphstats for effectively saving kind stat counts
  cmd/api/src/analysis/azure/queries.go
Labels: bug, api, release blocker

#538 fix: rootca chain logic, expand processing to uncollected domains, up…
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/test/integration/harnesses.go
  packages/go/analysis/ad/adcs.go
  packages/go/analysis/ad/adcscache.go
  packages/go/analysis/ad/queries.go
Labels: bug, api

#543 [BED-4258] ADCS ESC13 ExtendedByPolicy edge creation
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/test/integration/graph.go
  cmd/api/src/test/integration/harnesses.go
  packages/cue/bh/ad/ad.cue
  packages/go/analysis/ad/adcs.go
  packages/go/analysis/ad/esc_shared.go
  packages/go/graphschema/ad/ad.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: enhancement

#564 BED-4336: Cue file problem
  packages/cue/bh/ad/ad.cue
Labels: bug, api

#562 BED 4329: Add Sample Data and Link
  README.md
  cmd/ui/src/views/Explore/GraphView.tsx
  examples/sample-data/README.md
  examples/sample-data/ad_example_data.zip
  packages/javascript/bh-shared-ui/src/components/NoDataAlert/NoDataAlert.test.tsx
  packages/javascript/bh-shared-ui/src/components/NoDataAlert/NoDataAlert.tsx
Labels: documentation, user interface

#569 feat: add ESC2 pre-defined query
  packages/javascript/bh-shared-ui/src/commonSearches.tsx
Labels: enhancement, user interface

#577 Open password reset dialog when updating user to use username/password based authentication
  cmd/ui/src/views/Users/Users.test.tsx
  cmd/ui/src/views/Users/Users.tsx
  packages/javascript/bh-shared-ui/src/components/PasswordDialog/PasswordDialog.tsx
  packages/javascript/js-client-library/src/client.ts
  packages/javascript/js-client-library/src/types.ts
Labels: user interface
