Repository SpecterOps/BloodHound, pull requests merged in 2025-05, with the labels that each got.

#1422 fix: moved v6 only ingest assertions to the v6 specific assertions
  cmd/api/src/test/fixtures/fixtures/expected_ingest.go
Labels: api

#1419 fix: tier details object sort order
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/index.tsx
  packages/javascript/js-client-library/src/client.ts
Labels: bug, user interface

#1425 BED-5614: AzureRoleEligibilityScheduleInstance Ingest
  cmd/api/src/go.mod
  cmd/api/src/go.sum
  packages/cue/bh/azure/azure.cue
  packages/go/analysis/go.mod
  packages/go/analysis/go.sum
  packages/go/ein/azure.go
  packages/go/ein/azure_test.go
  packages/go/ein/go.mod
  packages/go/ein/go.sum
  packages/go/graphschema/azure/azure.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: api

#1438 BED-5869 fixed overflow
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DynamicDetails.tsx
Labels: bug, user interface

#1447 fix (api): BED-4699 - update static asset handler to return appropriate content headers
  cmd/api/src/api/static/static.go
  cmd/api/src/api/static/static_internal_test.go
  cmd/api/src/vendormocks/io/fs/mock.go
  cmd/api/src/vendormocks/vendor.go
Labels: api

#1420 BED-5811: Get rid of homepage redirect loop
  cmd/ui/src/views/Home/Home.tsx
  cmd/ui/src/views/Login.tsx
  packages/javascript/bh-shared-ui/src/hooks/useEnvironmentParams/useEnvironmentParams.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreParams/useExploreParams.tsx
  packages/javascript/bh-shared-ui/src/utils/searchParams/searchParams.ts
Labels: bug, user interface

#1413 BED-5847 -- Confusion on "Clear Database" confirmation prompt
  cmd/ui/src/views/DatabaseManagement/ConfirmationDialog.test.tsx
  cmd/ui/src/views/DatabaseManagement/ConfirmationDialog.tsx
  cmd/ui/src/views/DatabaseManagement/DatabaseManagement.test.tsx
  cmd/ui/src/views/DatabaseManagement/DatabaseManagement.tsx
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItem.tsx
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItemV2.tsx
  packages/javascript/bh-shared-ui/src/components/ConfirmationDialog.test.tsx
  packages/javascript/bh-shared-ui/src/components/ConfirmationDialog.tsx
  packages/javascript/bh-shared-ui/src/components/DeleteConfirmationDialog.test.tsx
  packages/javascript/bh-shared-ui/src/components/DeleteConfirmationDialog.tsx
  packages/javascript/bh-shared-ui/src/views/SSOConfiguration/SSOConfiguration.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SeedSelection.tsx
  packages/javascript/bh-shared-ui/src/views/Users/Users.tsx
Labels: user interface

#1454 BED-5884 - migration for tier management early access
  cmd/api/src/database/migration/migrations/v7.4.0.sql
Labels: api

#1431 feat: BED-5771 added tabs for tier management
  packages/javascript/bh-shared-ui/src/routes/index.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DetailsList.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DetailsList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/EntityInfoContent.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/SelectedDetails.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/BasicInfo.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SeedSelection.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorForm.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/TagForm.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/index.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/index.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/utils.tsx
Labels: enhancement, user interface

#1435 fix: BED-5861 fixed overflow
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DetailsList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.tsx
Labels: bug, user interface

#1426 BED-5615: Azure Ingest AZRoleManagementPolicyAssignment
  cmd/api/src/daemons/datapipe/azure_convertors.go
  cmd/api/src/go.mod
  packages/cue/bh/azure/azure.cue
  packages/go/ein/azure.go
  packages/go/ein/azure_test.go
  packages/go/graphschema/azure/azure.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: enhancement

#1456 fix: clear seeds on selector type switch
  cmd/api/src/daemons/datapipe/agt.go
  packages/javascript/bh-shared-ui/src/components/AssetGroupManagement/AssetGroupSelectorObjectSelect.test.tsx
  packages/javascript/bh-shared-ui/src/components/AssetGroupManagement/AssetGroupSelectorObjectSelect.tsx
  packages/javascript/bh-shared-ui/src/components/VirtualizedNodeList.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/InfoStyles/CollapsibleSection.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Cypher/Cypher.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DetailsList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DynamicDetails.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/SelectorList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/ObjectCountPanel.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/ObjectCountPanel.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/utils.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/BasicInfo.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SeedSelection.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorForm.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorFormContext.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/index.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/TierManagement.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/TierManagement.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/index.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/utils.tsx
Labels: bug, user interface

#1459 fix: selectorId empty check since it defaults to empty string now
  packages/javascript/bh-shared-ui/src/components/AssetGroupManagement/AssetGroupSelectorObjectSelect.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Cypher/Cypher.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Cypher/Cypher.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/BasicInfo.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorForm.tsx
Labels: bug, user interface

#1460 fix: BED-5893
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DetailsList.tsx
Labels: bug, user interface

#1465 fix:BED-5898 fixed width issue
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/EntityInfoPanel.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/SelectorList.tsx
Labels: bug, user interface

#1463 fix: cypher preview rerender and members list rendering
  packages/javascript/bh-shared-ui/src/views/TierManagement/Cypher/Cypher.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.tsx
Labels: bug, user interface

#1404 BED 5594: Generic Ingest Datapipe Updates
  cmd/api/src/api/v2/fileingest.go
  cmd/api/src/daemons/datapipe/convertors.go
  cmd/api/src/daemons/datapipe/decoders.go
  cmd/api/src/daemons/datapipe/fileops.go
  cmd/api/src/daemons/datapipe/fileops_test.go
  cmd/api/src/daemons/datapipe/genericingest.go
  cmd/api/src/daemons/datapipe/genericingest_integration_test.go
  cmd/api/src/daemons/datapipe/ingest.go
  cmd/api/src/daemons/datapipe/ingest_integration_test.go
  cmd/api/src/daemons/datapipe/jobs.go
  cmd/api/src/database/migration/migrations/v7.5.0.sql
  cmd/api/src/model/ingest.go
  cmd/api/src/model/unified_graph.go
  cmd/api/src/services/ingest/file_validator.go
  cmd/api/src/services/ingest/job.go
  cmd/api/src/services/ingest/jsonschema/node.json
  cmd/api/src/services/ingest/streamdecoder.go
  cmd/api/src/services/ingest/streamdecoder_test.go
  cmd/api/src/services/ingest/task.go
  cmd/api/src/test/integration/harnesses.go
  packages/cue/bh/common/common.cue
  packages/go/dawgs/drivers/neo4j/cypher.go
  packages/go/dawgs/drivers/pg/batch.go
  packages/go/dawgs/drivers/pg/query/format.go
  packages/go/dawgs/graph/kind.go
  packages/go/dawgs/graph/node.go
  packages/go/ein/ad.go
  packages/go/ein/azure.go
  packages/go/ein/azure_test.go
  packages/go/ein/incoming_models.go
  packages/go/ein/models.go
  packages/go/graphschema/common/common.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: enhancement, api

#1446 Remove back button support flag
  cmd/ui/src/App.test.tsx
  cmd/ui/src/components/AuthenticatedRoute/AuthenticatedRoute.test.tsx
  cmd/ui/src/components/GraphEdgeEvents.tsx
  cmd/ui/src/components/GraphEdgeEventsV2.tsx
  cmd/ui/src/components/GraphEvents.tsx
  cmd/ui/src/components/GraphEventsV2.tsx
  cmd/ui/src/components/SigmaChart.tsx
  cmd/ui/src/mocks/handlers/deepLinking.ts
  cmd/ui/src/mocks/handlers/index.ts
  cmd/ui/src/routes/index.ts
  cmd/ui/src/test-utils.jsx
  cmd/ui/src/views/Administration/Administration.test.tsx
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItem.test.tsx
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItem.tsx
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItemV2.tsx
  cmd/ui/src/views/Explore/ContextMenu/ContextMenu.test.tsx
  cmd/ui/src/views/Explore/ContextMenu/ContextMenu.tsx
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuV2.test.tsx
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuV2.tsx
  cmd/ui/src/views/Explore/ContextMenu/CopyMenuItem.test.tsx
  cmd/ui/src/views/Explore/ContextMenu/CopyMenuItem.tsx
  cmd/ui/src/views/Explore/ContextMenu/CopyMenuItemV2.tsx
  cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.test.tsx
  cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.tsx
  cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoHeader.test.tsx
  cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoHeader.tsx
  cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoPane.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoCollapsibleSction.test.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoContent.test.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.test.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoHeader.test.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoHeader.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoPanel.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoPanelContext.ts
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoPanelContextProvider.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityObjectInformation.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.tsx
  cmd/ui/src/views/Explore/ExploreSearch/switches/index.ts
  cmd/ui/src/views/Explore/ExploreSearch/switches/useCypherSearchSwitch.ts
  cmd/ui/src/views/Explore/ExploreSearch/switches/useNodeSearchSwitch.ts
  cmd/ui/src/views/Explore/ExploreSearch/switches/usePathfindingFilterSwitch.ts
  cmd/ui/src/views/Explore/ExploreSearch/switches/usePathfindingSearchSwitch.ts
  cmd/ui/src/views/Explore/GraphView.tsx
  cmd/ui/src/views/Explore/GraphViewFeatureToggle.tsx
  cmd/ui/src/views/Explore/GraphViewV2.tsx
  cmd/ui/src/views/GroupManagement/GroupManagement.tsx
  cmd/ui/src/views/QA/QA.tsx
  packages/javascript/bh-shared-ui/src/hooks/useAvailableEnvironments/useAvailableEnvironments.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useEdgeInfoItems.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useEdgeInfoItems.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useNodeSearch.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingSearch.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useInitialEnvironment/useInitialEnvironment.test.tsx
  packages/javascript/bh-shared-ui/src/mocks/handlers/tierHandlers.ts
Labels: user interface

#1476 fix: corrects an invalid update statement in the v7.4.0 migration file
  cmd/api/src/database/migration/migrations/v7.4.0.sql
Labels: bug

#1475 feat: BED-5910
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuV2.tsx
Labels: user interface

#1473 refactor user profile, update description
  packages/javascript/bh-shared-ui/src/views/UserProfile/UserProfile.tsx
Labels: user interface

#1466 Bed 5879 update devreadme
  DEVREADME.md
Labels: documentation

#1491 BED-5920 Node-Search-Z-Index
  cmd/api/src/api/v2/customnode_test.go
  cmd/ui/src/views/Explore/svgIcons.ts
  cmd/ui/tailwind.config.js
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useCustomNodeKinds.tsx
  packages/javascript/bh-shared-ui/src/utils/icons.ts
  packages/javascript/js-client-library/src/client.ts
  packages/javascript/js-client-library/src/responses.ts
  packages/javascript/js-client-library/src/types.ts
Labels: bug, user interface

#1500 docs: fix wording
  docs/resources/edges/cross-forest-trust.mdx
  docs/resources/edges/same-forest-trust.mdx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CrossForestTrust/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/SameForestTrust/General.tsx
Labels: documentation, external

#1471 BED-5911: Explore sagas cleanup
  cmd/ui/src/ducks/entityinfo/actions.ts
  cmd/ui/src/ducks/entityinfo/index.ts
  cmd/ui/src/ducks/entityinfo/reducer.ts
  cmd/ui/src/ducks/entityinfo/types.ts
  cmd/ui/src/ducks/explore/actions.ts
  cmd/ui/src/ducks/explore/index.ts
  cmd/ui/src/ducks/explore/reducer.ts
  cmd/ui/src/ducks/explore/saga.ts
  cmd/ui/src/ducks/explore/types.ts
  cmd/ui/src/ducks/index.ts
  cmd/ui/src/ducks/searchbar/saga.ts
  cmd/ui/src/rootSaga.ts
  cmd/ui/src/store.ts
  cmd/ui/src/views/Explore/ContextMenu/ContextMenu.test.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoPanel.tsx
  cmd/ui/src/views/GroupManagement/GroupManagement.tsx
  packages/javascript/bh-shared-ui/src/components/AssetGroupManagement/AssetGroupSelectorObjectSelect.tsx
  packages/javascript/bh-shared-ui/src/components/ExploreSearchCombobox/ExploreSearchCombobox.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useNodeSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingSearch.ts
  packages/javascript/bh-shared-ui/src/store/index.ts
  packages/javascript/bh-shared-ui/src/store/searchbar/actions.ts
  packages/javascript/bh-shared-ui/src/store/searchbar/index.ts
  packages/javascript/bh-shared-ui/src/store/searchbar/reducer.ts
  packages/javascript/bh-shared-ui/src/store/searchbar/types.ts
  packages/javascript/bh-shared-ui/src/types.ts
  packages/javascript/bh-shared-ui/src/views/Explore/BasicObjectInfoFields.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/NodeSearch.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/PathfindingSearch.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/index.ts
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/types.ts
Labels: user interface

#1506 Add cli option to clear quarantine on MacOS
  docs/get-started/quickstart/community-edition-quickstart.mdx
Labels: documentation

#1513 fix (api): pass any type for last seen value
  cmd/api/src/migrations/manifest.go
Labels: bug, api
