Repository SpecterOps/BloodHound, pull requests merged in 2025-02, with the labels that each got.

#1119 Fix breakage in ADCS integration tests in BHE
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/analysis/ad/ntlm_integration_test.go
  cmd/api/src/analysis/ad/post.go
  packages/go/analysis/ad/adcs.go
  packages/go/analysis/ad/adcscache.go
  packages/go/analysis/ad/ntlm.go
Labels: bug, api

#1120 BP-1302: Reduced the height at which nav scroll activates
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
Labels: user interface

#1124 BED-5353A: Hide version number when nav collapsed
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.test.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
Labels: user interface

#1125 BED-5369: Added back data-testid attributes
  cmd/ui/src/components/MainNav/MainNavData.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.test.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/types.ts
Labels: user interface

#1127 BED-5379: Added download collectors to nav and changed order
  cmd/ui/src/components/MainNav/MainNavData.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/Download.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/index.ts
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
Labels: user interface

#1126 BED-5377: Enable recreating the default admin user with environment variable
  cmd/api/src/bootstrap/server.go
  cmd/api/src/config/config.go
  cmd/api/src/config/default.go
  cmd/api/src/services/entrypoint.go
  docker-compose.dev.yml
  examples/docker-compose/docker-compose.yml
Labels: enhancement, tooling

#1128 BED-5895: Underline color same as text color in active route in admin nav
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/SubNav.tsx
Labels: bug, user interface

#1133 chore: update containers base images
  packages/go/dawgs/graph/types.go
  packages/python/beagle/beagle/plan/yarn.py
  tools/docker-compose/api.Dockerfile
Labels: api, infrastructure, release blocker

#1134 BED-5410: Fix invalid slog parameters in measure logs
  packages/go/analysis/azure/tenant.go
  packages/go/analysis/impact/id_aggregator.go
  packages/go/dawgs/ops/traversal.go
Labels: bug, api

#1139 fix: update pre-built searches to avoid potentially comparing defined…
  packages/javascript/bh-shared-ui/src/commonSearches.test.ts
  packages/javascript/bh-shared-ui/src/commonSearches.ts
Labels: bug, user interface, release blocker

#1143 BED-5419: Revert mistaken change to make pg the global default driver
  .env.example
  .github/config/integration.config.json
  cmd/api/src/config/default.go
  docker-compose.dev.yml
  dockerfiles/configs/bloodhound.config.json
  examples/docker-compose/.env.example
  examples/docker-compose/bloodhound.config.json
  examples/docker-compose/docker-compose.yml
  examples/helm/values.yaml
  local-harnesses/build.config.json.template
  local-harnesses/integration.config.json.template
Labels: api

#1149 feat: Adds new feature flag `back_button_support`
  cmd/api/src/database/migration/migrations/v7.1.0.sql
Labels: api

#1093 BED-5026 CoerceAndRelayNTLMToLDAP(s) Post Processing
  cmd/api/src/analysis/ad/ntlm_integration_test.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToLDAP.json
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToLDAP.svg
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToLDAPS.json
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToLDAPS.svg
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToSMB.json
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToSMB.svg
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMtoSMB.json
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMtoSMB.svg
  packages/cue/bh/ad/ad.cue
  packages/go/analysis/ad/ad.go
  packages/go/analysis/ad/ntlm.go
  packages/go/analysis/ad/queries.go
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/common/common.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/edgeTypes.tsx
Labels: enhancement

#1146 BED-5346: Preventing Graph Control buttons' text from collapsing
  cmd/ui/src/components/GraphButtons/GraphButtons.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx
  cmd/ui/src/views/Explore/GraphView.tsx
Labels: bug, user interface

#1162 BED-5484 NTLM feature flag
  cmd/api/src/analysis/ad/post.go
  cmd/api/src/daemons/datapipe/analysis.go
  cmd/api/src/database/migration/migrations/v7.1.0.sql
  cmd/api/src/model/appcfg/flag.go
  packages/go/analysis/ad/ntlm.go
Labels: enhancement

#1173 BED-5434: Fix login with leading/trailing spaces in username
  cmd/api/src/api/v2/auth/login.go
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
Labels: bug, api

#1174 BED-5026 Fix LDAP(S) IsDC Usage From String Comparison To Bool Comparison
  cmd/api/src/test/integration/harnesses.go
  packages/go/analysis/ad/ntlm.go
Labels: bug

#1155 Improve group shortcutting and ADCS logic
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/analysis/post_integration_test.go
  packages/go/analysis/ad/ad.go
  packages/go/analysis/ad/adcs.go
  packages/go/analysis/ad/adcscache.go
  packages/go/analysis/ad/esc1.go
  packages/go/analysis/ad/esc10.go
  packages/go/analysis/ad/esc13.go
  packages/go/analysis/ad/esc3.go
  packages/go/analysis/ad/esc4.go
  packages/go/analysis/ad/esc6.go
  packages/go/analysis/ad/esc9.go
  packages/go/analysis/ad/esc_shared.go
  packages/go/analysis/ad/post.go
  packages/go/analysis/ad/queries.go
Labels: enhancement, external

#1165 chore: Updating OpenAPI doc to update `get` to `put`
  docs/hc/en-us/reference/eula/accept-eula.mdx
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/eula.accept-eula.yaml
Labels: documentation, api

#1168 BED-5489: Downgraded bh-shared-ui react-router-dom package to match BHE/CE projects
  .yarn/cache/@types-cookie-npm-0.6.0-1f4c3f48f0-5edce79957.zip
  .yarn/cache/cookie-npm-1.0.2-7a4273d897-2c5a621414.zip
  .yarn/cache/react-router-dom-npm-7.1.3-4ea8242f95-c076e81315.zip
  .yarn/cache/react-router-npm-7.1.3-690b1d22ca-4e0261232e.zip
  .yarn/cache/set-cookie-parser-npm-2.7.1-0e92d9e679-2ef8b35109.zip
  .yarn/cache/turbo-stream-npm-2.4.0-e0cec53097-e36f52ed40.zip
  packages/javascript/bh-shared-ui/package.json
  packages/javascript/bh-shared-ui/src/utils/searchParams/searchParams.ts
  yarn.lock
Labels: user interface

#1176 BED-5018 NTLM Ingestion Updates
  cmd/api/src/daemons/datapipe/convertors.go
  cmd/ui/src/queryClient.ts
  packages/go/ein/ad.go
  packages/go/ein/ad_test.go
  packages/go/ein/incoming_models.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/CoerceAndRelayNTLMToADCS.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/CoerceAndRelayNTLMToSMB.tsx
Labels: enhancement

#1183 Small fixes in NTLM
  packages/go/analysis/ad/ntlm.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/CoerceAndRelayNTLMToADCS.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/CoerceAndRelayNTLMToLDAP.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/CoerceAndRelayNTLMToLDAPS.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/CoerceAndRelayNTLMToSMB.tsx
Labels: bug, api

#1184 BED-5484 updated General copy to reference Relay Target instead of co…
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/WindowsAbuse.tsx
Labels: bug
