Repository SpecterOps/BloodHound, pull requests merged in 2025-03, with the labels that each got.

#1195 BED-5526 removed artifact of event log based NTLM saved query
  packages/javascript/bh-shared-ui/src/commonSearches.ts
Labels: bug

#1196 fix: update t0 label const name to disambiguate from high value
  cmd/ui/src/views/GroupManagement/GroupManagement.tsx
  packages/javascript/bh-shared-ui/src/constants.ts
Labels: bug, user interface, release blocker

#1197 Remove OwnsRaw and WriteOwnerRaw from ACLRelationships
  packages/cue/bh/ad/ad.cue
  packages/go/graphschema/ad/ad.go
Labels: bug, api

#1198 BED-5525 Set NTLM Feature Flag Default To Disabled & Update NTLMSMB General Copy
  cmd/api/src/database/migration/migrations/v7.1.0.sql
  packages/go/analysis/ad/ntlm.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/General.tsx
Labels: bug

#1200 BED-5484 Removed extra step from NTLM [LDAP, LDAPS, ADCS] WindowsAbuse copy
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/WindowsAbuse.tsx
Labels: bug

#1199 BED-5532 - PostgreSQL Batch Update
  packages/go/cypher/models/pgsql/translate/building.go
  packages/go/cypher/models/pgsql/translate/delete.go
  packages/go/cypher/models/pgsql/translate/expansion.go
  packages/go/cypher/models/pgsql/translate/expression.go
  packages/go/cypher/models/pgsql/translate/function.go
  packages/go/cypher/models/pgsql/translate/indexed.go
  packages/go/cypher/models/pgsql/translate/match.go
  packages/go/cypher/models/pgsql/translate/model.go
  packages/go/cypher/models/pgsql/translate/node.go
  packages/go/cypher/models/pgsql/translate/pattern.go
  packages/go/cypher/models/pgsql/translate/predicate.go
  packages/go/cypher/models/pgsql/translate/projection.go
  packages/go/cypher/models/pgsql/translate/query.go
  packages/go/cypher/models/pgsql/translate/relationship.go
  packages/go/cypher/models/pgsql/translate/renamer.go
  packages/go/cypher/models/pgsql/translate/tracking.go
  packages/go/cypher/models/pgsql/translate/translation.go
  packages/go/cypher/models/pgsql/translate/translator.go
  packages/go/cypher/models/pgsql/translate/traversal.go
  packages/go/cypher/models/pgsql/translate/update.go
  packages/go/cypher/models/pgsql/translate/with.go
  packages/go/dawgs/drivers/pg/batch.go
  packages/go/dawgs/drivers/pg/driver.go
  packages/go/dawgs/drivers/pg/transaction.go
Labels: enhancement, api

#1175 chore: remove unnecessary or outdated extensions from recommendations
  .vscode/extensions.json
Labels: documentation

#1193 BED-5522: Unable to hover/click entire label
  cmd/ui/src/components/GraphEdgeEvents.tsx
Labels: bug, user interface

#1166 Bed 5520: searchTab and searchType on tab change
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.tsx
  cmd/ui/src/views/Explore/GraphViewV2.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreParams/useExploreParams.tsx
Labels: enhancement, user interface

#1210 BED-5448: entityRelationshipEndpoints
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx
  packages/javascript/bh-shared-ui/src/utils/content.ts
Labels: user interface

#1225 BED-5447: Deep linking cypher search
  cmd/ui/src/views/Explore/ExploreSearch/CommonSearches.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/CommonSearches.tsx
  cmd/ui/src/views/Explore/ExploreSearch/CypherSearch.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/CypherSearch.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.tsx
  cmd/ui/src/views/Explore/ExploreSearch/NodeSearch.tsx
  cmd/ui/src/views/Explore/ExploreSearch/PathfindingSearch.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/PathfindingSearch.tsx
  cmd/ui/src/views/Explore/ExploreSearch/PathfindingSwapButton.tsx
  cmd/ui/src/views/Explore/ExploreSearch/switches/index.ts
  cmd/ui/src/views/Explore/ExploreSearch/switches/useCypherSearchSwitch.ts
  cmd/ui/src/views/Explore/ExploreSearch/switches/useNodeSearchSwitch.ts
  cmd/ui/src/views/Explore/ExploreSearch/switches/usePathfindingSearchSwitch.ts
  docs/assets/community-edition-pill-tag.svg
  docs/assets/enterprise-AND-community-edition-pill-tag.svg
  docs/assets/enterprise-edition-pill-tag.svg
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/index.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/cypherSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/index.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/nodeSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/pathfindingSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useCypherSearch.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useCypherSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useExploreGraph.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useExploreGraph.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useNodeSearch.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useNodeSearch/useNodeSearch.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useNodeSearch/useNodeSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingSearch.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/utils.ts
Labels: user interface

#1223 BED-5448: Deep linking support for composition and relationship search queries
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoContent.test.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.test.tsx
  cmd/ui/src/views/GroupManagement/GroupManagement.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/compositionSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/index.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/relationshipSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/utils.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useExploreGraph.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useExploreGraph.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreParams/useExploreParams.tsx
  packages/javascript/bh-shared-ui/src/utils/content.ts
  packages/javascript/bh-shared-ui/src/utils/parseItemId.ts
Labels: enhancement, blocked, user interface

#1226 BED-5460: Deep Linking support for Node Context Menu
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItemV2.tsx
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuV2.test.tsx
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuV2.tsx
  cmd/ui/src/views/Explore/ContextMenu/CopyMenuItemV2.tsx
Labels: enhancement, user interface

#1233 BED-5538: Support Export Graph data functionality in deep linking
  cmd/ui/src/components/GraphButtons/GraphButtons.test.tsx
  cmd/ui/src/components/GraphButtons/GraphButtons.tsx
  cmd/ui/src/views/Explore/GraphView.tsx
  cmd/ui/src/views/Explore/GraphViewV2.tsx
Labels: user interface

#1236 BED-5544 remove self relay from SMB and LDAP(S)
  cmd/api/src/analysis/ad/ntlm_integration_test.go
  cmd/api/src/test/integration/harnesses.go
  packages/go/analysis/ad/ntlm.go
Labels: bug

#1238 BED-4757: copyright cleanup
  cmd/ui/src/components/GraphEdgeEventsV2.tsx
  cmd/ui/src/components/GraphEventsV2.tsx
  cmd/ui/src/views/Explore/GraphViewV2.tsx
  cmd/ui/src/views/QA/QA.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/compositionSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/cypherSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/nodeSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/pathfindingSearch.ts
Labels: user interface

#1242 BED-5583: Panel is now in sync with URL params
  cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.test.tsx
  cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoContent.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoPanel.tsx
  packages/javascript/bh-shared-ui/src/utils/index.ts
  packages/javascript/bh-shared-ui/src/utils/panelSectionsParams.ts
Labels: bug, user interface

#1244 BED-4948: Set initial node label color based on dark mode setting
  cmd/ui/src/components/SigmaChart.tsx
Labels: user interface

#1229 BED-5546 CoerceAndRelayNTLMToSMB Composition To Relay Targets
  cmd/api/src/analysis/ad/ntlm_integration_test.go
  cmd/api/src/test/integration/harnesses.go
  packages/go/analysis/ad/ad.go
  packages/go/analysis/ad/ntlm.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/CoerceAndRelayNTLMToSMB.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/RelayTargets.tsx
Labels: bug

#1249 BED-5591: GroupManagement missing member counts (and some bugs)
  cmd/ui/src/hooks/useInitialEnvironment/useInitialEnvironment.test.tsx
  cmd/ui/src/hooks/useInitialEnvironment/useInitialEnvironment.tsx
  cmd/ui/src/views/GroupManagement/GroupManagement.tsx
  cmd/ui/src/views/QA/QA.tsx
  packages/javascript/bh-shared-ui/rollup.config.js
  packages/javascript/bh-shared-ui/src/components/GroupManagementContent/GroupManagementContent.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/RelayTargets.tsx
Labels: bug, user interface

#1253 BED-5592: Sync empty search fields for deep linking
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useCypherSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useNodeSearch.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useNodeSearch.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingSearch.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingSearch.ts
Labels: user interface

#1163 BED-5301/5298: PenTest Result: Internal IP Address Disclosure AND Rate limit Bypass
  cmd/api/src/api/middleware/rate_limit.go
  cmd/api/src/api/middleware/rate_limit_test.go
  cmd/api/src/api/registration/registration.go
  cmd/api/src/api/registration/v2.go
  cmd/api/src/database/migration/migrations/v7.2.0.sql
  cmd/api/src/database/parameters_test.go
  cmd/api/src/go.mod
  cmd/api/src/go.sum
  cmd/api/src/model/appcfg/parameter.go
Labels: bug

#1254 Fix broken tests
  cmd/api/src/analysis/ad/ntlm_integration_test.go
  cmd/api/src/test/integration/harnesses.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/Opsec.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingFilters.test.tsx
Labels: bug

#1260 BED-5564: Deny Users From Self-Deleting Via The API
  cmd/api/src/api/v2/auth/auth.go
  cmd/api/src/api/v2/auth/auth_test.go
Labels: bug, api

#1274 Update traversable-edges.mdx
  docs/resources/edges/traversable-edges.mdx
Labels: documentation, ticketed, external

#1272 BED-5560: v7.2.0 Release Notes
  docs/docs.json
  docs/resources/release-notes/2024-12-09-v6-3-0.mdx
  docs/resources/release-notes/v7-2-0.mdx
Labels: documentation

#1294 BED-5638: GetEdgeComposition Now Parses Node IDs Into 64bit Integers
  cmd/api/src/api/v2/edge.go
Labels: bug, api

#1292 BED-5505: Entity/Edge Panels Deep linking cleanup for parity with BHE
  cmd/ui/src/views/Explore/EdgeInfo/EdgeInfoPane.tsx
Labels: user interface
