Repository SpecterOps/BloodHound, pull requests merged in 2025-07, with the labels that each got.

#1637 BED-6109 zone management default view
  packages/javascript/bh-shared-ui/src/routes/index.tsx
Labels: bug, user interface

#1644 Add Incoming Forest Trust Builders selector
  cmd/api/src/database/migration/migrations/v7.4.0.sql
Labels: enhancement, external

#1661 chore: add test ids
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx
  cmd/ui/src/views/ZoneManagement/InfoHeader.tsx
  packages/javascript/bh-shared-ui/src/components/GraphButton/GraphButton.tsx
  packages/javascript/bh-shared-ui/src/components/GraphControls/GraphControls.test.tsx
  packages/javascript/bh-shared-ui/src/components/GraphControls/GraphControls.tsx
  packages/javascript/bh-shared-ui/src/components/GraphMenu/GraphMenu.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/SubNav.tsx
  packages/javascript/bh-shared-ui/src/components/SearchCurrentNodes/SearchCurrentNodes.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/CypherSearch.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Cypher/Cypher.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DynamicDetails.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/ObjectCountPanel.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/Save.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/BasicInfo.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/DeleteSelectorButton/DeleteSelectorButton.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/SeedSelection.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/TagForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/TagForm.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/Summary.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/SummaryList.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/ZoneManagement.tsx
Labels: user interface

#1667 fix: failing unit test
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuZoneManagementEnabled.test.tsx
Labels: bug, user interface

#1681 fix: update tag id usage for object return value
  cmd/ui/src/views/ZoneManagement/InfoHeader.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DynamicDetails.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/Save.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/Save.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/TagForm.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/Summary.tsx
Labels: bug, user interface

#1694 feat(Database Management): add deletion by source kind
  cmd/api/src/daemons/datapipe/delete.go
  cmd/api/src/daemons/datapipe/delete_integration_test.go
  cmd/ui/src/views/DatabaseManagement/DatabaseManagement.test.tsx
  cmd/ui/src/views/DatabaseManagement/DatabaseManagement.tsx
  packages/go/lab/generic/graph.go
  packages/javascript/bh-shared-ui/src/components/SourceKindsCheckboxes/SourceKindsCheckboxes.test.tsx
  packages/javascript/bh-shared-ui/src/components/SourceKindsCheckboxes/SourceKindsCheckboxes.tsx
  packages/javascript/bh-shared-ui/src/components/SourceKindsCheckboxes/index.ts
  packages/javascript/bh-shared-ui/src/components/index.ts
  packages/javascript/js-client-library/src/client.ts
  packages/javascript/js-client-library/src/requests.ts
Labels: enhancement, user interface

#1701 chore: new tag command for stbernard to allow us to generate tag outputs
  .vscode/settings.json
  packages/go/stbernard/command/command.go
  packages/go/stbernard/command/tag/tag.go
Labels: tooling

#1704 BED-6233: form-data vuln resolution
  .yarn/cache/call-bind-apply-helpers-npm-1.0.2-3eedbea3bb-b2863d74fc.zip
  .yarn/cache/dunder-proto-npm-1.0.1-90eb6829db-149207e36f.zip
  .yarn/cache/es-define-property-npm-1.0.1-3fc6324f1c-0512f4e5d5.zip
  .yarn/cache/es-object-atoms-npm-1.1.1-362d8043c2-214d376728.zip
  .yarn/cache/es-set-tostringtag-npm-2.1.0-4e55705d3f-789f35de4b.zip
  .yarn/cache/form-data-npm-4.0.0-916facec2d-01135bf867.zip
  .yarn/cache/form-data-npm-4.0.4-10eb4ef9c3-9b7788836d.zip
  .yarn/cache/get-intrinsic-npm-1.3.0-35558f27b6-301008e448.zip
  .yarn/cache/get-proto-npm-1.0.1-4d30bac614-4fc96afdb5.zip
  .yarn/cache/gopd-npm-1.2.0-df89ffa78e-cc6d8e655e.zip
  .yarn/cache/has-symbols-npm-1.1.0-9aa7dc2ac1-b2316c7302.zip
  .yarn/cache/math-intrinsics-npm-1.1.0-9204d80e7d-0e513b29d1.zip
  package.json
  packages/javascript/js-client-library/.gitignore
  packages/javascript/js-client-library/package-lock.json
  yarn.lock
Labels: release blocker

#1714 fix: power user app config read
  cmd/api/src/auth/role.go
  cmd/api/src/database/migration/migrations/v8.0.0.sql
Labels: bug

#1674 Support HasSIDHistroy on Groups
  cmd/api/src/services/graphify/convertors.go
  packages/go/ein/ad.go
  packages/go/ein/ad_test.go
  packages/go/ein/incoming_models.go
Labels: enhancement, api

#1529 AD special identities update
  cmd/api/src/daemons/datapipe/analysis.go
  cmd/api/src/test/integration/harnesses.go
  packages/cue/bh/ad/ad.cue
  packages/go/analysis/ad/ad.go
  packages/go/analysis/ad/ad_integration_test.go
  packages/go/analysis/ad/ntlm.go
  packages/go/analysis/ad/owns.go
  packages/go/analysis/ad/post.go
  packages/go/analysis/ad/queries.go
  packages/go/analysis/ad/wellknown/prefix.go
  packages/go/analysis/ad/wellknown/suffix.go
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/common/common.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ClaimSpecialIdentity/Abuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ClaimSpecialIdentity/ClaimSpecialIdentity.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ClaimSpecialIdentity/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ClaimSpecialIdentity/Opsec.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ClaimSpecialIdentity/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/index.tsx
  packages/javascript/bh-shared-ui/src/edgeTypes.tsx
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: enhancement, external

#1688 feat: added Analyze now button
  cmd/ui/src/views/BloodHoundConfiguration/BloodHoundConfiguration.tsx
  packages/javascript/bh-shared-ui/src/components/AnalyzeNowConfiguration/AnalyzeNowConfiguration.test.tsx
  packages/javascript/bh-shared-ui/src/components/AnalyzeNowConfiguration/AnalyzeNowConfiguration.tsx
  packages/javascript/bh-shared-ui/src/components/AnalyzeNowConfiguration/AnalyzeNowConfirmDialog.tsx
  packages/javascript/bh-shared-ui/src/components/AnalyzeNowConfiguration/index.ts
  packages/javascript/bh-shared-ui/src/components/index.ts
  packages/javascript/js-client-library/src/client.ts
Labels: enhancement, user interface

#1677 BED-6172 feat: add environment parameter to PZ member endpoints
  cmd/api/src/api/constant.go
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/api/v2/assetgrouptags_test.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.members.counts.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.members.yaml
  packages/go/openapi/src/schemas/model.asset-group-tags-member.yaml
Labels: enhancement, api

#1699 chore: clean up old tests
  .github/config/integration.config.json
  .golangci.json
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/analysis/ad/ntlm_integration_test.go
  cmd/api/src/analysis/azure/queries_test.go
  cmd/api/src/analysis/hybrid/hybrid_integration_test.go
  cmd/api/src/api/v2/analysisrequest_integration_test.go
  cmd/api/src/api/v2/apiclient/agi.go
  cmd/api/src/api/v2/apiclient/analysisrequest.go
  cmd/api/src/api/v2/apiclient/apiclient.go
  cmd/api/src/api/v2/apiclient/app_config.go
  cmd/api/src/api/v2/apiclient/audit.go
  cmd/api/src/api/v2/apiclient/auth.go
  cmd/api/src/api/v2/apiclient/credential.go
  cmd/api/src/api/v2/apiclient/cypherquery.go
  cmd/api/src/api/v2/apiclient/database_wipe.go
  cmd/api/src/api/v2/apiclient/entity.go
  cmd/api/src/api/v2/apiclient/flags.go
  cmd/api/src/api/v2/apiclient/ingest.go
  cmd/api/src/api/v2/apiclient/mocks/credential.go
  cmd/api/src/api/v2/apiclient/savedqueries.go
  cmd/api/src/api/v2/apiclient/version.go
  cmd/api/src/api/v2/app_config_integration_test.go
  cmd/api/src/api/v2/audit_integration_test.go
  cmd/api/src/api/v2/auth/auth_integration_test.go
  cmd/api/src/api/v2/azure_integration_test.go
  cmd/api/src/api/v2/collectors_integration_test.go
  cmd/api/src/api/v2/collectors_test.go
  cmd/api/src/api/v2/cypherquery_integration_test.go
  cmd/api/src/api/v2/database_wipe_integration_test.go
  cmd/api/src/api/v2/datapipe_integration_test.go
  cmd/api/src/api/v2/datapipe_test.go
  cmd/api/src/api/v2/file_uploads_integration_test.go
  cmd/api/src/api/v2/integration/agi.go
  cmd/api/src/api/v2/integration/api.go
  cmd/api/src/api/v2/integration/apiclient.go
  cmd/api/src/api/v2/integration/audit.go
  cmd/api/src/api/v2/integration/auth.go
  cmd/api/src/api/v2/integration/clients.go
  cmd/api/src/api/v2/integration/config.go
  cmd/api/src/api/v2/integration/context.go
  cmd/api/src/api/v2/integration/ingest.go
  cmd/api/src/api/v2/integration/reconciliation.go
  cmd/api/src/api/v2/kinds_integration_test.go
  cmd/api/src/auth/role_test.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/migration/migration_integration_test.go
  cmd/api/src/migrations/migrations_integration_test.go
  cmd/api/src/services/graphify/genericingest_integration_test.go
  cmd/api/src/services/graphify/ingest_integration_test.go
  cmd/api/src/test/integration/context.go
  cmd/api/src/test/integration/database.go
  cmd/api/src/test/integration/dawgs.go
  cmd/api/src/test/integration/graph.go
  cmd/api/src/test/integration/utils/integration-config.json
  cmd/api/src/test/lab/fixtures/apiclient.go
  cmd/api/src/test/lab/harnesses/basic.go
  packages/go/stbernard/cmdrunner/cmdrunner.go
  packages/go/stbernard/workspace/golang/tester.go
Labels: api, tooling

#1713 BED-5943: Privilege Zones UX Updates
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/BasicInfo.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/ObjectSelect.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/SeedSelection.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/SelectorForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/SelectorForm.tsx
Labels: user interface

#1743 feat: AdminSDHolder Protected - BED-6286
  cmd/api/src/database/migration/migrations/v8.1.0.sql
  cmd/ui/public/img/BHCE_Vertical_RedField.svg
  packages/cue/bh/ad/ad.cue
  packages/go/graphschema/ad/ad.go
  packages/javascript/bh-shared-ui/src/commonSearchesAGI.ts
  packages/javascript/bh-shared-ui/src/commonSearchesAGT.ts
  packages/javascript/bh-shared-ui/src/graphSchema.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DetailsList.test.tsx
Labels: enhancement, user interface, external
