Repository SpecterOps/BloodHound, pull requests merged in 2025-09, with the labels that each got.

#1829 feat(BED-6245): BloodHound icon refresh
  .yarn/cache/@types-react-helmet-npm-6.1.11-6d6a281744-e329d8ad82.zip
  .yarn/cache/react-fast-compare-npm-3.2.2-45b585a872-2071415b4f.zip
  .yarn/cache/react-helmet-npm-6.1.0-20fd5447ff-a4998479da.zip
  .yarn/cache/react-side-effect-npm-2.1.2-c18e5fd8bd-c5eb1f42b4.zip
  cmd/ui/index.html
  cmd/ui/package.json
  cmd/ui/public/favicon-dark.ico
  cmd/ui/public/favicon-light.ico
  cmd/ui/public/favicon.ico
  cmd/ui/public/img/BHCE_Vertical_RedField.svg
  cmd/ui/public/img/banner-ce-dark-mode.png
  cmd/ui/public/img/banner-ce-light-mode.png
  cmd/ui/public/img/logo-secondary-transparent-full.svg
  cmd/ui/public/img/logo-transparent-full.svg
  cmd/ui/public/manifest.json
  cmd/ui/src/App.tsx
  cmd/ui/src/components/MainNav/MainNavData.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/BHCELogo.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/BHCELogoFull.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/BHELogoFull.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/CaretDown.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/CaretUp.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/Compass.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/Download.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/FilterOutline.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/Info.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/LargeRightArrow.tsx
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/index.ts
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/utils.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.test.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/types.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/SummaryCard.tsx
  yarn.lock
Labels: enhancement, user interface

#1855 fix(FeatureFlag): fallback to 'disabled' view on 403
  packages/javascript/bh-shared-ui/src/components/FeatureFlag/FeatureFlag.tsx
  packages/javascript/bh-shared-ui/src/hooks/useFeatureFlags.tsx
Labels: bug, user interface

#1840 BED-5918: Database Error occurring when timing out user sessions
  cmd/api/src/database/auth.go
Labels: bug

#1871 fix(OpenGraph): BED-5383-fix - add ingest job ID to completed task in BHCE pipeline
  cmd/api/src/daemons/datapipe/pipeline.go
Labels: bug, api

#1874 BED-6331: Added formatting function to display comma separated numbers
  packages/javascript/bh-shared-ui/src/utils/index.ts
  packages/javascript/bh-shared-ui/src/utils/numberFormatting.test.ts
  packages/javascript/bh-shared-ui/src/utils/numberFormatting.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/SummaryCard.tsx
Labels: user interface

#1883 chore: v8.1.3 merge back
  cmd/api/src/migrations/manifest.go
  packages/go/analysis/ad/ad.go
  packages/go/analysis/ad/ad_integration_test.go
Labels: api

#1878 feat (api): Add Get Users Minimal Endpoint - BED-6448
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/sort.go
  cmd/api/src/api/sort_test.go
  cmd/api/src/api/v2/auth/users.go
  cmd/api/src/api/v2/auth/users_test.go
  cmd/api/src/auth/permission.go
  cmd/api/src/database/auth.go
  cmd/api/src/database/db.go
  cmd/api/src/database/migration/migrations/v8.2.0.sql
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/bh-users.bloodhound-users-minimal.yaml
  packages/go/openapi/src/schemas/model.users-minimal.yaml
Labels: enhancement, api

#1890 Add a Parameter For Stale Clients
  cmd/api/src/daemons/changelog/cache_internal_test.go
  cmd/api/src/daemons/changelog/changelog_integration_test.go
  cmd/api/src/database/migration/migrations/v8.2.0.sql
  cmd/api/src/model/appcfg/parameter.go
Labels: api

#1898 BED-6494 -- Delete Query Confirmation Modal
  packages/javascript/bh-shared-ui/src/components/PrebuiltSearchList/PrebuiltSearchList.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CommonSearches.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/ConfirmDeleteQueryDialog.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/QuerySearchFilter.tsx
Labels: bug, user interface

#1899 BED-6490--Copy Update
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CommonSearches.test.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CommonSearches.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/QuerySearchFilter.tsx
Labels: enhancement, user interface

#1902 fix(agt): tag update request dirty fields
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Save/TagForm/TagForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Save/TagForm/TagForm.tsx
Labels: bug, user interface

#1904 fix(agt): search bar overlap create buttons fix
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/SearchBar.tsx
Labels: bug, user interface

#1910 Bump Sharphound to Latest Version
  dockerfiles/bloodhound.Dockerfile
  tools/docker-compose/api.Dockerfile
Labels: infrastructure

#1903 Stage/v8.2.0 into main
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/sort.go
  cmd/api/src/api/sort_test.go
  cmd/api/src/api/v2/auth/users.go
  cmd/api/src/api/v2/auth/users_test.go
  cmd/api/src/auth/permission.go
  cmd/api/src/database/auth.go
  cmd/api/src/database/db.go
  cmd/api/src/database/migration/migrations/v8.2.0.sql
  cmd/api/src/model/appcfg/parameter.go
  cmd/ui/src/views/Explore/utils.test.ts
  cmd/ui/src/views/Explore/utils.ts
  cmd/ui/src/views/PrivilegeZones/InfoHeader.tsx
  dockerfiles/bloodhound.Dockerfile
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/bh-users.bloodhound-users-minimal.yaml
  packages/go/openapi/src/schemas/model.users-minimal.yaml
  packages/javascript/bh-shared-ui/src/components/PrebuiltSearchList/ListItemActionMenu.tsx
  packages/javascript/bh-shared-ui/src/components/PrebuiltSearchList/PrebuiltSearchList.test.tsx
  packages/javascript/bh-shared-ui/src/components/PrebuiltSearchList/PrebuiltSearchList.tsx
  packages/javascript/bh-shared-ui/src/hooks/useEnvironmentIdList.tsx
  packages/javascript/bh-shared-ui/src/hooks/useFeatureFlags.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CommonSearches.test.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CommonSearches.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/ConfirmDeleteQueryDialog.test.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/ConfirmDeleteQueryDialog.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/CypherSearchMessage.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/QuerySearchFilter.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/SaveQueryDialog.test.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/SavedQueryPermissions.test.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/SavedQueryPermissions.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/ObjectCountPanel.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/SearchBar.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Save/TagForm/TagForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Save/TagForm/TagForm.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Summary/Summary.tsx
  packages/javascript/js-client-library/src/client.ts
  packages/javascript/js-client-library/src/types.ts
  tools/docker-compose/api.Dockerfile
Labels: release

#1933 fix: cancel the scrollbar rave
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/MembersList.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/SelectorsList.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/TagList.test.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/TagList.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Details/utils.tsx
  packages/javascript/bh-shared-ui/src/views/PrivilegeZones/Save/TagForm/TagForm.tsx
Labels: bug, user interface

#1943 BED-6547--Safari Select Label z-index
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/SavedQueries/QuerySearchFilter.tsx
Labels: bug, user interface
