Repository SpecterOps/BloodHound, pull requests merged in 2025-08, with the labels that each got.

#1741 BED-6232: Explore Table data fetch refactor
  cmd/ui/src/hooks/useSigmaExploreGraph/useSigmaExploreGraph.tsx
  cmd/ui/src/views/Explore/GraphView.test.tsx
  cmd/ui/src/views/Explore/GraphView.tsx
  packages/javascript/bh-shared-ui/src/components/ExploreTable/ExploreTable.test.tsx
  packages/javascript/bh-shared-ui/src/components/ExploreTable/ExploreTable.tsx
  packages/javascript/bh-shared-ui/src/components/ExploreTable/ExploreTableDataCell/ExploreTableDataCell.tsx
  packages/javascript/bh-shared-ui/src/components/ExploreTable/ExploreTableHeaderCell.tsx
  packages/javascript/bh-shared-ui/src/components/ExploreTable/ManageColumnsComboBox/ManageColumnsComboBox.tsx
  packages/javascript/bh-shared-ui/src/components/ExploreTable/ManageColumnsComboBox/ManageColumnsListItem.tsx
  packages/javascript/bh-shared-ui/src/components/ExploreTable/explore-table-test-props.ts
  packages/javascript/bh-shared-ui/src/components/ExploreTable/explore-table-utils.test.ts
  packages/javascript/bh-shared-ui/src/components/ExploreTable/explore-table-utils.ts
  packages/javascript/bh-shared-ui/src/components/ExploreTable/useExploreTableRowsAndColumns.tsx
  packages/javascript/bh-shared-ui/src/mocks/factories/explore.ts
  packages/javascript/bh-shared-ui/src/mocks/factories/index.ts
  packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.ts
  packages/javascript/bh-shared-ui/src/views/Explore/BasicObjectInfoFields.tsx
Labels: user interface

#1757 chore: bump SharpHound Version
  dockerfiles/bloodhound.Dockerfile
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DetailsList.test.tsx
  tools/docker-compose/api.Dockerfile
Labels: api

#1765 Add deb packaging for direct-installation on distributions like Kali.
  debian/README.md
  debian/bhapi.json.default
  debian/bloodhound.dirs
  debian/bloodhound.install
  debian/bloodhound.postinst
  debian/changelog
  debian/control
  debian/copyright
  debian/generate_changelog.sh
  debian/rules
  packages/go/graphify/main.go
  packages/go/stbernard/analyzers/js/js.go
  packages/go/stbernard/environment/environment.go
  packages/go/stbernard/main.go
  packages/go/stbernard/workspace/golang/build.go
  packages/go/stbernard/workspace/golang/generate.go
  packages/go/stbernard/workspace/golang/mod.go
  packages/go/stbernard/workspace/yarn/yarn.go
Labels: tooling

#1756 fix(agt): form component alignment
  .yarn/cache/@bloodhoundenterprise-doodleui-npm-1.0.0-alpha.22-46a4a0aea1-0c4bbbc0bc.zip
  .yarn/cache/@bloodhoundenterprise-doodleui-npm-1.0.0-alpha.24-0b3ccd3321-2ec7bfab8a.zip
  .yarn/cache/@radix-ui-react-label-npm-2.1.0-5d222548ab-462f3b47f4.zip
  .yarn/cache/@radix-ui-react-label-npm-2.1.7-2edf88c6a6-6fe47ff695.zip
  .yarn/cache/@radix-ui-react-primitive-npm-2.1.3-6080896851-01f82e4bad.zip
  .yarn/cache/@radix-ui-react-slot-npm-1.2.3-6e45e6d89b-2731089e15.zip
  .yarn/cache/react-hook-form-npm-7.61.1-1f3f0b62d8-2cd69df3fb.zip
  cmd/ui/package.json
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuZoneManagementEnabled.tsx
  packages/javascript/bh-shared-ui/package.json
  packages/javascript/bh-shared-ui/src/components/EntityInfo/EntityInfoDataTableList.test.tsx
  packages/javascript/bh-shared-ui/src/components/EntityInfo/EntityInfoHeader.test.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/SubNav.tsx
  packages/javascript/bh-shared-ui/src/components/VirtualizedNodeList.tsx
  packages/javascript/bh-shared-ui/src/hooks/useAssetGroupTags/useAssetGroupTags.tsx
  packages/javascript/bh-shared-ui/src/hooks/useZoneParams/index.ts
  packages/javascript/bh-shared-ui/src/hooks/useZoneParams/useZonePathParams.tsx
  packages/javascript/bh-shared-ui/src/mocks/handlers/zoneHandlers.ts
  packages/javascript/bh-shared-ui/src/utils/searchParams/useAppNavigate.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Cypher/Cypher.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DetailsList.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DetailsList.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/SelectorsList.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/BasicInfo.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/SeedSelection.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/SelectorForm.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/SelectorForm/types.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/TagForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/TagForm.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/utils.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/Summary.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/SummaryCard.tsx
  packages/javascript/js-client-library/src/requests.ts
  yarn.lock
Labels: bug, user interface

#1766 BED-6306: added ETAC table, model layer, and api layer
  cmd/api/src/api/access_control_list.go
  cmd/api/src/api/access_control_list_test.go
  cmd/api/src/api/v2/auth/auth_test.go
  cmd/api/src/database/access_control_list.go
  cmd/api/src/database/access_control_list_integration_test.go
  cmd/api/src/database/database_integration_test.go
  cmd/api/src/database/db.go
  cmd/api/src/database/migration/migrations/v8.1.0.sql
  cmd/api/src/database/mocks/db.go
  cmd/api/src/model/audit.go
  cmd/api/src/model/auth.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/schemas/model.user.yaml
Labels: api

#1779 fix: remove timezone setting in the configuration file due to the image no longer supporting it
  .github/config/postgresql.conf
  local-harnesses/postgresql.conf.template
Labels: infrastructure, tooling

#1772 chore: prelim work for pathfinding edge filter context menu
  cmd/ui/src/components/SigmaChart/GraphEvents.tsx
  cmd/ui/src/rendering/utils/utils.test.ts
  cmd/ui/src/rendering/utils/utils.ts
  cmd/ui/src/utils.test.ts
  cmd/ui/src/utils.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingFilters.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/usePathfindingFilters.ts
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/utils.ts
  packages/javascript/bh-shared-ui/src/utils/array.test.ts
  packages/javascript/bh-shared-ui/src/utils/array.ts
  packages/javascript/bh-shared-ui/src/utils/index.ts
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/EdgeFilter.tsx
Labels: enhancement, user interface

#1737 feat(FinishedJobsLog): rework table
  packages/javascript/bh-shared-ui/src/components/DataTable.tsx
  packages/javascript/bh-shared-ui/src/components/FinishedJobsTable/FinishedJobsTable.test.tsx
  packages/javascript/bh-shared-ui/src/components/FinishedJobsTable/FinishedJobsTable.tsx
  packages/javascript/bh-shared-ui/src/components/FinishedJobsTable/index.ts
  packages/javascript/bh-shared-ui/src/components/StatusIndicator.test.tsx
  packages/javascript/bh-shared-ui/src/components/StatusIndicator.tsx
  packages/javascript/bh-shared-ui/src/components/index.ts
  packages/javascript/bh-shared-ui/src/providers/NotificationProvider/hooks.ts
  packages/javascript/bh-shared-ui/src/utils/datetime.test.ts
  packages/javascript/bh-shared-ui/src/utils/datetime.ts
  packages/javascript/bh-shared-ui/src/utils/finishedJobs.test.ts
  packages/javascript/bh-shared-ui/src/utils/finishedJobs.ts
  packages/javascript/bh-shared-ui/src/utils/index.ts
  packages/javascript/js-client-library/src/client.ts
  packages/javascript/js-client-library/src/responses.ts
Labels: enhancement, user interface

#1672 Update ADCS saved searches
  packages/javascript/bh-shared-ui/src/commonSearchesAGI.ts
  packages/javascript/bh-shared-ui/src/commonSearchesAGT.ts
Labels: enhancement, external

#1653 Add DCFor in pathfinding filter
  packages/javascript/bh-shared-ui/src/edgeTypes.tsx
Labels: bug, external

#1800 fix: get self query key consistency
  packages/javascript/bh-shared-ui/src/hooks/usePermissions/usePermissions.tsx
Labels: bug, user interface

#1654 Make ManageCA and ManageCertificate traversable
  packages/cue/bh/ad/ad.cue
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/common/common.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCA/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ManageCertificates/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/edgeTypes.tsx
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: enhancement, external

#1808 fix: update react hook form
  .yarn/cache/call-bind-npm-1.0.8-4145a20621-aa2899bce9.zip
  .yarn/cache/call-bound-npm-1.0.4-359cfa32c7-2f6399488d.zip
  .yarn/cache/for-each-npm-0.3.5-b74c5c5ba7-3c986d7e11.zip
  .yarn/cache/is-typed-array-npm-1.1.15-33aa18e28f-ea7cfc46c2.zip
  .yarn/cache/react-hook-form-npm-7.45.2-49cc9a73cd-023ca091f2.zip
  .yarn/cache/sha.js-npm-2.4.11-14868df4ca-ebd3f59d4b.zip
  .yarn/cache/sha.js-npm-2.4.12-bc0424125d-9ec0fe39cc.zip
  .yarn/cache/to-buffer-npm-1.2.1-d977d5fb59-a683dcf19b.zip
  .yarn/cache/typed-array-buffer-npm-1.0.3-bddcba0c25-3fb91f0735.zip
  .yarn/cache/which-typed-array-npm-1.1.19-e664d1e89c-162d2a07f6.zip
  cmd/ui/package.json
  package.json
  yarn.lock
Labels: bug, user interface

#1801 fix (api): Overwrite SharedWithUsers - BED-6388
  cmd/api/src/database/saved_queries_permissions.go
  cmd/api/src/database/saved_queries_permissions_integration_test.go
Labels: bug, api

#1819 BED-6402: SearchCurrentNodes fix
  packages/javascript/bh-shared-ui/src/components/SearchCurrentNodes/SearchCurrentNodes.tsx
Labels: bug, user interface

#1792 feat: BED-5783
  cmd/ui/src/views/ZoneManagement/InfoHeader.tsx
  packages/javascript/bh-shared-ui/src/components/VirtualizedNodeList.tsx
  packages/javascript/bh-shared-ui/src/mocks/factories/zoneManagement.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/SearchBar.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/SearchBar.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/utils.tsx
  packages/javascript/js-client-library/src/client.ts
  packages/javascript/js-client-library/src/responses.ts
  packages/javascript/js-client-library/src/types.ts
Labels: enhancement, user interface

#1818 feat(agt): tag glyphs
  cmd/ui/src/App.test.tsx
  cmd/ui/src/components/SigmaChart/SigmaChart.tsx
  cmd/ui/src/hooks/useSigmaExploreGraph/useSigmaExploreGraph.test.tsx
  cmd/ui/src/hooks/useSigmaExploreGraph/useSigmaExploreGraph.tsx
  cmd/ui/src/views/Administration/Administration.tsx
  cmd/ui/src/views/Explore/GraphView.test.tsx
  cmd/ui/src/views/Explore/GraphView.tsx
  cmd/ui/src/views/Explore/svgIcons.ts
  cmd/ui/src/views/Explore/utils.test.ts
  cmd/ui/src/views/Explore/utils.ts
  packages/javascript/bh-shared-ui/src/components/ExploreTable/ExploreTable.test.tsx
  packages/javascript/bh-shared-ui/src/components/GraphControls/GraphControls.test.tsx
  packages/javascript/bh-shared-ui/src/components/GraphControls/GraphControls.tsx
  packages/javascript/bh-shared-ui/src/components/SearchCurrentNodes/SearchCurrentNodes.tsx
  packages/javascript/bh-shared-ui/src/components/SearchResultItem/SearchResultItem.tsx
  packages/javascript/bh-shared-ui/src/hooks/useAssetGroupTags/useAssetGroupTags.tsx
  packages/javascript/bh-shared-ui/src/hooks/useCustomNodeKinds.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/queries/utils.ts
  packages/javascript/bh-shared-ui/src/mocks/factories/explore.ts
  packages/javascript/bh-shared-ui/src/mocks/factories/zoneManagement.ts
  packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.ts
  packages/javascript/bh-shared-ui/src/utils/icons.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/ObjectCountPanel.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/DetailsRoot.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/Summary.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/SummaryList.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/SummaryList.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/ZoneManagement.tsx
  packages/javascript/js-client-library/src/types.ts
Labels: enhancement, user interface

#1841 feat: enable file logging
  .github/config/integration.config.json
  cmd/api/src/bootstrap/initializer.go
  cmd/api/src/bootstrap/util.go
  cmd/api/src/cmd/bhapi/main.go
  cmd/api/src/config/config.go
  dockerfiles/configs/bloodhound.config.json
  examples/docker-compose/bloodhound.config.json
  examples/helm/templates/cmbh.yaml
  local-harnesses/build.config.json.template
  local-harnesses/integration.config.json.template
Labels: api
