Repository SpecterOps/BloodHound, pull requests merged in 2025-06, with the labels that each got.

#1480 BED-4762 - (BHCE) Sticky layout between searches
  cmd/ui/src/components/GraphEvents.tsx
  cmd/ui/src/ducks/global/actions.ts
  cmd/ui/src/ducks/global/reducer.ts
  cmd/ui/src/ducks/global/types.ts
  cmd/ui/src/views/Explore/GraphView.tsx
Labels: user interface

#1541 chore: remove paths-ignore for docs
  .github/workflows/build-ui.yml
  .github/workflows/ci.yml
  .github/workflows/run-tests.yml
  .github/workflows/static-code-analysis.yml
  .github/workflows/vuln-scan.yml
Labels: infrastructure

#1543 (docs):bhcs-475:Update SAML page to reflect V2 URLs
  docs/assets/image-2-52.png
  docs/manage-bloodhound/auth/saml-entra-id.mdx
Labels: documentation

#1520 BED-5228 UI: Create Tier Button
  cmd/api/src/api/csv.go
  cmd/api/src/api/v2/flag_test.go
  cmd/api/src/database/featureflags.go
  cmd/api/src/model/appcfg/flag.go
  cmd/api/src/model/audit.go
  cmd/ui/src/views/TierManagement/InfoHeader.tsx
  packages/javascript/bh-shared-ui/src/mocks/factories/tierManagement.ts
  packages/javascript/bh-shared-ui/src/routes/index.tsx
  packages/javascript/bh-shared-ui/src/utils/index.ts
  packages/javascript/bh-shared-ui/src/utils/tagUrlValue.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/SelectorList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SeedSelection.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/SelectorForm/SelectorForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/TagForm.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Save/index.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/TierManagement.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/index.tsx
Labels: user interface

#1470 feat: Adding validations to user creations form
  packages/javascript/bh-shared-ui/src/components/CreateUserForm/CreateUserForm.test.tsx
  packages/javascript/bh-shared-ui/src/components/CreateUserForm/CreateUserForm.tsx
  packages/javascript/bh-shared-ui/src/components/UpdateUserForm/UpdateUserForm.test.tsx
  packages/javascript/bh-shared-ui/src/components/UpdateUserForm/UpdateUserForm.tsx
  packages/javascript/bh-shared-ui/src/constants.ts
  packages/javascript/bh-shared-ui/src/test-utils.jsx
Labels: bug, user interface

#1557 BED-5225 summary view
  packages/javascript/bh-shared-ui/src/components/AppIcon/Icons/DownArrow.tsx
  packages/javascript/bh-shared-ui/src/routes/index.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DetailsList.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/DetailsList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/EntityInfo/SelectorList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/MembersList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/utils.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Summary/Summary.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Summary/SummaryList.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Summary/SummaryList.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/TierManagement.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/fragments.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/fragments.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/utils.tsx
Labels: enhancement, user interface

#1532 Bed 5281 create tier
  cmd/api/src/api/error.go
  cmd/api/src/api/registration/v2.go
  cmd/api/src/database/assetgrouptags.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/db.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/model/assetgrouptags.go
  cmd/api/src/model/audit.go
  packages/go/dawgs/drivers/neo4j/driver.go
  packages/go/dawgs/drivers/pg/driver.go
  packages/go/dawgs/graph/graph.go
  packages/go/dawgs/graph/mocks/graph.go
  packages/go/dawgs/graph/switch.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.yaml
  packages/go/openapi/src/schemas/model.asset-group-tag-request.yaml
Labels: enhancement, api

#1545 BED-5283: API - Delete Tier/Label
  .github/workflows/run-tests.yml
  .github/workflows/static-code-analysis.yml
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/daemons/datapipe/agt.go
  cmd/api/src/database/assetgrouptags.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/model/audit.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.yaml
Labels: documentation, enhancement, api

#1552 BED-5282 feat: tier update
  cmd/api/src/api/error.go
  cmd/api/src/database/assetgrouphistory.go
  cmd/api/src/database/assetgrouptags.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/mocks/db.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.yaml
  packages/go/openapi/src/schemas/model.asset-group-tag-update.yaml
Labels: enhancement, api

#1590 BED-6036: Update Go Container Build From 1.23.9 to 1.23.10
  dockerfiles/bloodhound.Dockerfile
Labels: infrastructure

#1591 BED-6029: Bumps packages recommended from dependabot
  .yarn/cache/brace-expansion-npm-1.1.11-fb95eb05ad-faf34a7bb0.zip
  .yarn/cache/brace-expansion-npm-1.1.12-329e9ad7a1-12cb6d6310.zip
  .yarn/cache/vite-npm-5.4.14-4903607bfe-7360661da0.zip
  .yarn/cache/vite-npm-5.4.19-6d369030b0-c15af65f23.zip
  cmd/ui/package.json
  packages/javascript/bh-shared-ui/package.json
  packages/javascript/bh-shared-ui/src/components/GraphControls/GraphControls.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreTableAutoDisplay/useExploreTableAutoDisplay.test.tsx
  yarn.lock
Labels: user interface

#1593 chore: BED-5924 - added new file ingest and testing functions
  cmd/api/src/analysis/ad/ad_integration_test.go
  packages/go/lab/arrows/graph.go
  packages/go/lab/generic/graph.go
Labels: api, tooling

#1581 feat(api): BED-5967 Implements Keys for node table view
  cmd/api/src/api/marshalling.go
  cmd/api/src/api/v2/cypherquery.go
  cmd/api/src/api/v2/cypherquery_test.go
  cmd/api/src/go.tools.mod
  cmd/api/src/model/unified_graph.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/cypher.graphs.cypher.yaml
  packages/go/openapi/src/schemas/model.unified-graph.graph.w.property.keys.yaml
Labels: enhancement, api

#1576 feat: BED-5225
  packages/javascript/bh-shared-ui/src/routes/index.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/Details.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/Summary.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/SummaryList.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Summary/SummaryList.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/ZoneManagement.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/ZoneManagementContext.tsx
Labels: enhancement, user interface

#1595 feat (api): Bed 5196 - Import/Export Custom Queries
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/v2/saved_queries.go
  cmd/api/src/api/v2/saved_queries_test.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/database/saved_queries.go
  cmd/api/src/database/saved_queries_permissions.go
  cmd/api/src/model/audit.go
  cmd/api/src/model/saved_queries_permissions.go
  cmd/api/src/services/upload/streamdecoder.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/cypher.saved-queries.export.multiple.yaml
  packages/go/openapi/src/paths/cypher.saved-queries.export.yaml
  packages/go/openapi/src/paths/cypher.saved-queries.import.yaml
  packages/go/openapi/src/responses/unsupported-media-type.yaml
  packages/go/openapi/src/schemas/model.saved-queries.transferable.yaml
Labels: enhancement, api

#1606 BED-4884: Incorrect Hierarchy Name Fix
  .golangci.json
  cmd/api/src/analysis/azure/post.go
  cmd/api/src/go.mod
  cmd/api/src/go.sum
  packages/go/analysis/azure/management_group.go
  packages/go/analysis/azure/post.go
  packages/go/analysis/go.mod
  packages/go/analysis/go.sum
  packages/go/analysis/post_integration_test.go
  packages/go/bomenc/go.mod
  packages/go/bomenc/go.sum
  packages/go/crypto/go.mod
  packages/go/crypto/go.sum
  packages/go/ein/azure.go
  packages/go/ein/go.mod
  packages/go/ein/go.sum
  packages/go/lab/go.mod
  packages/go/lab/go.sum
  packages/go/schemagen/go.mod
  packages/go/schemagen/go.sum
  packages/go/stbernard/go.mod
  packages/go/stbernard/go.sum
Labels: bug, api

#1622 Rebase on main for v7.5.1 merge-back
  cmd/api/src/daemons/datapipe/datapipe.go
  cmd/api/src/go.mod
  cmd/api/src/go.sum
  cmd/api/src/services/graphify/genericingest.go
  cmd/api/src/services/graphify/ingest.go
  cmd/api/src/services/graphify/ingest_integration_test.go
  cmd/api/src/services/graphify/tasks.go
  packages/go/analysis/go.mod
  packages/go/analysis/go.sum
  packages/go/bomenc/go.mod
  packages/go/bomenc/go.sum
  packages/go/cache/go.mod
  packages/go/cache/go.sum
  packages/go/crypto/go.mod
  packages/go/crypto/go.sum
  packages/go/ein/go.mod
  packages/go/ein/go.sum
  packages/go/graphschema/go.mod
  packages/go/graphschema/go.sum
  packages/go/lab/go.mod
  packages/go/lab/go.sum
  packages/go/schemagen/go.mod
  packages/go/schemagen/go.sum
  packages/go/stbernard/go.mod
  packages/go/stbernard/go.sum
Labels: release blocker

#1611 BED-5896: Mark /api/v2/asset-groups/{id}/members as deprecated in OpenAPI docs
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/asset-isolation.asset-groups.id.members.yaml
  packages/go/openapi/src/paths/custom-nodes.custom-nodes.name.yaml
  packages/go/openapi/src/paths/custom-nodes.custom-nodes.yaml
Labels: bug, documentation

#1592 BED-6003 Analysis Toggle
  packages/javascript/bh-shared-ui/src/mocks/factories/zoneManagement.ts
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Details/DynamicDetails.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/SalesMessage.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/SalesMessage.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/TagForm.test.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/Save/TagForm/TagForm.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/ZoneManagement.tsx
  packages/javascript/bh-shared-ui/src/views/ZoneManagement/ZoneManagementContext.tsx
  packages/javascript/js-client-library/src/requests.ts
  packages/javascript/js-client-library/src/types.ts
Labels: user interface

#1508 BED-5695 feat: explore UI tiering updates
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItemV2.tsx
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItemZoneManagementEnabled.test.tsx
  cmd/ui/src/views/Explore/ContextMenu/AssetGroupMenuItemZoneManagementEnabled.tsx
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuZoneManagementEnabled.test.tsx
  cmd/ui/src/views/Explore/ContextMenu/ContextMenuZoneManagementEnabled.tsx
  cmd/ui/src/views/Explore/GraphView.tsx
  packages/javascript/js-client-library/src/requests.ts
Labels: enhancement, user interface
