Repository SpecterOps/BloodHound, pull requests merged in 2025-01, with the labels that each got.

#1018 Fix abuse info around read LAPS password narrative
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
  packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/AllExtendedRights/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GenericAll/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/Owns/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ReadLAPSPassword/General.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ReadLAPSPassword/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ReadLAPSPassword/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ReadLAPSPassword/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteDacl/WindowsAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/LinuxAbuse.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/References.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/WriteOwner/WindowsAbuse.tsx
Labels: documentation, external

#1015 BED-5036 implement post processing for CoerceAndRelayNTLMToSMB
  cmd/api/src/analysis/ad/ntlm_integration_test.go
  cmd/api/src/api/v2/auth/oidc.go
  cmd/api/src/api/v2/auth/saml.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToSMB.json
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToSMB.svg
  packages/cue/bh/ad/ad.cue
  packages/go/analysis/ad/ntlm.go
  packages/go/graphschema/ad/ad.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: enhancement

#1057 bloodhound.Dockerfile needs to point to SpecterOps org to find *hound releases
  README.md
  dockerfiles/bloodhound.Dockerfile
  tools/docker-compose/api.Dockerfile
Labels: bug

#1060 fix: include all asset files in static assets embed.FS
  cmd/api/src/api/static/assets.go
Labels: bug

#1059 Update go.work for go version
  go.work
Labels: api

#1082 BED-5303: Add tailwind
  .yarn/cache/@alloc-quick-lru-npm-5.2.0-eb83517088-bdc35758b5.zip
  .yarn/cache/any-promise-npm-1.3.0-f34eeaa7e7-0ee8a9bdbe.zip
  .yarn/cache/arg-npm-5.0.2-2f5805a547-6c69ada1a9.zip
  .yarn/cache/autoprefixer-npm-10.4.20-dd5fd05d27-187cec2ec3.zip
  .yarn/cache/browserslist-npm-4.24.4-2fdeb5face-64074bf6cf.zip
  .yarn/cache/camelcase-css-npm-2.0.1-90d1b6df08-1cec2b3b3d.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001692-6af96beb31-484113e3fa.zip
  .yarn/cache/chokidar-npm-3.6.0-3c413a828f-d2f29f4997.zip
  .yarn/cache/commander-npm-4.1.1-22a0fe921b-d7b9913ff9.zip
  .yarn/cache/cssesc-npm-3.0.0-15ec56f86f-f8c4ababff.zip
  .yarn/cache/dlv-npm-1.1.3-187c903a21-d7381bca22.zip
  .yarn/cache/electron-to-chromium-npm-1.5.82-d8ff622776-9d438663cc.zip
  .yarn/cache/escalade-npm-3.2.0-19b50dd48f-47b029c83d.zip
  .yarn/cache/fast-glob-npm-3.3.3-2a653be532-0704d7b85c.zip
  .yarn/cache/fraction.js-npm-4.3.7-c2c7e95a8e-e1553ae3f0.zip
  .yarn/cache/glob-npm-10.4.5-8c63175f05-0bc725de5e.zip
  .yarn/cache/is-core-module-npm-2.16.1-a54837229e-6ec5b3c42d.zip
  .yarn/cache/jackspeak-npm-3.4.3-546bfad080-be31027fc7.zip
  .yarn/cache/jiti-npm-1.21.7-9b00518619-9cd20dabf8.zip
  .yarn/cache/lilconfig-npm-3.1.3-74a77377bb-644eb10830.zip
  .yarn/cache/lru-cache-npm-10.4.3-30c10b861a-6476138d21.zip
  .yarn/cache/micromatch-npm-4.0.8-c9570e4aca-79920eb634.zip
  .yarn/cache/minimatch-npm-9.0.5-9aa93d97fa-2c035575ed.zip
  .yarn/cache/minipass-npm-7.1.2-3a5327d36d-2bfd325b95.zip
  .yarn/cache/mz-npm-2.7.0-ec3cef4ec2-8427de0ece.zip
  .yarn/cache/nanoid-npm-3.3.8-d22226208b-dfe0adbc0c.zip
  .yarn/cache/node-releases-npm-2.0.19-b123ed6240-917dbced51.zip
  .yarn/cache/normalize-range-npm-0.1.2-bec5e259e2-9b2f14f093.zip
  .yarn/cache/object-hash-npm-3.0.0-d941e0cabe-80b4904bb3.zip
  .yarn/cache/package-json-from-dist-npm-1.0.1-4631a88465-58ee9538f2.zip
  .yarn/cache/path-scurry-npm-1.11.1-aaf8c339af-890d5abcd5.zip
  .yarn/cache/picocolors-npm-1.1.1-4fede47cf1-e1cf46bf84.zip
  .yarn/cache/pify-npm-2.3.0-8b63310934-9503aaeaf4.zip
  .yarn/cache/pirates-npm-4.0.6-a8ec571a43-46a65fefaf.zip
  .yarn/cache/postcss-import-npm-15.1.0-8b9e86f900-7bd04bd8f0.zip
  .yarn/cache/postcss-js-npm-4.0.1-2c4ee70bf3-5c1e83efea.zip
  .yarn/cache/postcss-load-config-npm-4.0.2-319bcff9ca-7c27dd3801.zip
  .yarn/cache/postcss-nested-npm-6.2.0-389c2a5f75-2c86ecf2d0.zip
  .yarn/cache/postcss-npm-8.5.1-90fd898a99-cfdcfcd019.zip
  .yarn/cache/postcss-selector-parser-npm-6.1.2-46a8e03b00-ce9440fc42.zip
  .yarn/cache/postcss-value-parser-npm-4.2.0-3cef602a6a-819ffab0c9.zip
  .yarn/cache/read-cache-npm-1.0.0-00fa89ed05-cffc728b9e.zip
  .yarn/cache/resolve-npm-1.22.10-d6fd9cdec7-ab7a32ff40.zip
  .yarn/cache/resolve-patch-d29ff41c85-8aac1e4e46.zip
  .yarn/cache/source-map-js-npm-1.2.1-b9a47d7e1a-4eb0cd997c.zip
  .yarn/cache/sucrase-npm-3.35.0-60ad876a0c-9fc5792a9a.zip
  .yarn/cache/tailwindcss-npm-3.4.17-403059edc1-bda962f30e.zip
  .yarn/cache/thenify-all-npm-1.6.0-96309bbc8b-dba7cc8a23.zip
  .yarn/cache/thenify-npm-3.3.1-030bedb22c-84e1b804bf.zip
  .yarn/cache/ts-interface-checker-npm-0.1.13-0c7b064494-20c29189c2.zip
  .yarn/cache/update-browserslist-db-npm-1.1.2-59b122fef6-088d2bad8d.zip
  .yarn/cache/yaml-npm-2.7.0-bb348b356b-6e8b2f9b9d.zip
  cmd/ui/package.json
  cmd/ui/postcss.config.js
  cmd/ui/public/mockServiceWorker.js
  cmd/ui/src/main.tsx
  cmd/ui/src/styles/index.css
  cmd/ui/tailwind.config.js
  tools/docker-compose/ui.Dockerfile
  yarn.lock
Labels: user interface

#1084 BED-5124: "No Data" alert
  cmd/ui/src/components/NoDataDialogWithLinks.tsx
  cmd/ui/src/views/Explore/GraphView.tsx
  packages/javascript/bh-shared-ui/src/components/NoDataAlert/NoDataAlert.test.tsx
  packages/javascript/bh-shared-ui/src/components/NoDataAlert/NoDataAlert.tsx
  packages/javascript/bh-shared-ui/src/components/NoDataAlert/index.tsx
  packages/javascript/bh-shared-ui/src/components/NoDataDialog/NoDataDialog.test.tsx
  packages/javascript/bh-shared-ui/src/components/NoDataDialog/NoDataDialog.tsx
  packages/javascript/bh-shared-ui/src/components/index.ts
Labels: user interface

#1094 BED-5329: Stabilize mainline with `prepare-for-codereview`
  cmd/api/src/api/v2/auth/auth_test.go
  cmd/api/src/bootstrap/util.go
  cmd/api/src/cmd/bhapi/main.go
  cmd/api/src/cmd/dawgs-harness/main.go
  cmd/api/src/config/default.go
  cmd/ui/src/components/LoginPage.tsx
  cmd/ui/src/components/NoDataDialogWithLinks.tsx
  cmd/ui/src/main.tsx
  cmd/ui/src/styles/index.css
  cmd/ui/src/views/Explore/GraphView.tsx
  docs/hc/images/image-192.svg
  docs/hc/images/image-193.svg
  docs/hc/images/image-194.svg
  docs/hc/images/image-195.svg
  docs/hc/images/image-38.svg
  docs/logo/dark.svg
  docs/logo/light.svg
  packages/go/bhlog/bhlog.go
  packages/go/schemagen/main.go
  packages/go/stbernard/main.go
Labels: tooling

#1092 feat: BED-5132 - aggregate risk and posture data
  cmd/api/src/api/error.go
  cmd/api/src/database/dataquality.go
  cmd/api/src/database/db.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/queries/graph.go
  cmd/api/src/queries/mocks/graph.go
Labels: enhancement, api

#1047 feat: bed-5132 - updated openapi spec for posture page api contract
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/attack-paths.attack-paths.finding-trends.yaml
  packages/go/openapi/src/paths/risk-posture.posture-history.data-type.yaml
  packages/go/openapi/src/schemas/enum.posture-history-type.yaml
Labels: documentation, enhancement, api

#1107 chore: introduce Or method to threadsafekindbitmap
  local-harnesses/build.config.json.template
  local-harnesses/integration.config.json.template
  packages/go/dawgs/graph/types.go
Labels: api

#1111 Bed 5258
  cmd/api/src/api/v2/helpers.go
  packages/javascript/js-client-library/src/client.ts
Labels: api

#1116 chore: expand collapse nav with tw hover and grouping
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.test.tsx
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
Labels: user interface

#1058 CoerceAndRelayNTLMtoADCS Post Processing
  cmd/api/src/analysis/ad/adcs_integration_test.go
  cmd/api/src/analysis/ad/ntlm_integration_test.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToADCS.json
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMToSMB.svg
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMtoADCS.svg
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMtoSMB.json
  cmd/api/src/test/integration/harnesses/CoerceAndRelayNTLMtoSMB.svg
  packages/cue/bh/ad/ad.cue
  packages/go/analysis/ad/adcs.go
  packages/go/analysis/ad/adcscache.go
  packages/go/analysis/ad/esc3.go
  packages/go/analysis/ad/ntlm.go
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/common/common.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: enhancement

#1118 BP-1303: Replace truncated version with wrapped version number when nav collapsed
  packages/javascript/bh-shared-ui/src/components/Navigation/MainNav.tsx
Labels: user interface
