Repository SpecterOps/BloodHound, pull requests merged in 2025-04, with the labels that each got.

#1227 BED-5252: API Task - Tier/Label Details
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/api/v2/assetgrouptags_test.go
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.yaml
  packages/go/openapi/src/paths/attack-paths.domains.id.details.yaml
  packages/go/openapi/src/schemas/model.asset-group-tag.yaml
  packages/go/openapi/src/schemas/null.boolean.yaml
  packages/go/openapi/src/schemas/null.string.yaml
Labels: enhancement, api

#1247 BED-5273
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/api/v2/assetgrouptags_test.go
  cmd/api/src/database/assetgrouptags.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/model/assetgrouptags.go
  cmd/api/src/model/filter.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.selectors.id.yaml
  packages/go/openapi/src/paths/attack-paths.domains.id.details.yaml
  packages/go/openapi/src/schemas/model.asset-group-tags-selector-seed.yaml
  packages/go/openapi/src/schemas/model.asset-group-tags-selector.yaml
Labels: documentation, enhancement, api

#1300 BED-5669: HTTPEnrollmentEndpoints will now be properly ingested
  packages/go/ein/ad.go
Labels: bug

#1305 BED-5648: Export graph data test warning cleanup
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.test.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.test.tsx
  packages/javascript/bh-shared-ui/src/mocks/handlers/tierHandlers.ts
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/CypherSearch.test.tsx
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.test.tsx
Labels: user interface

#1310 BED-5673: ParseDomainTrusts float Parsing For TrustedAttributes
  packages/cue/bh/ad/ad.cue
  packages/go/ein/ad.go
  packages/go/ein/ad_test.go
  packages/go/graphschema/ad/ad.go
  packages/javascript/bh-shared-ui/src/graphSchema.ts
Labels: bug

#1320 fix: coerce edges not added to post processed relationships properly
  packages/go/analysis/ad/post.go
Labels: bug

#1312 BED-5576: Unset overflow when FixedSizeList has fewer than 2 nodes
  packages/javascript/bh-shared-ui/src/components/VirtualizedNodeList.tsx
Labels: bug, user interface

#1313 Bed 5498: Move node search component to `bh-shared-ui`
  cmd/ui/public/img/logo-animated.gif
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearch.tsx
  cmd/ui/src/views/Explore/ExploreSearch/ExploreSearchV2.tsx
  cmd/ui/src/views/Explore/ExploreSearch/useNodeSearchSwitch.ts
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/NodeSearch.tsx
  packages/javascript/bh-shared-ui/src/views/Explore/ExploreSearch/index.ts
Labels: user interface

#1296 BED-5269: Tiering update selector
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/api/v2/assetgrouptags_test.go
  cmd/api/src/database/assetgrouptags.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/model/assetgrouptags.go
  cmd/api/src/model/audit.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.selectors.id.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.selectors.yaml
  packages/go/openapi/src/schemas/model.asset-group-tags-selector-request.yaml
  packages/go/openapi/src/schemas/model.asset-group-tags-selector-response.yaml
  packages/go/openapi/src/schemas/model.asset-group-tags-selector-seed-request.yaml
  packages/go/openapi/src/schemas/model.asset-group-tags-selector-seed-response.yaml
Labels: api

#1329 [BED-5709] Correct AzureHound CE documentation link
  packages/javascript/bh-shared-ui/src/components/DocumentationLinks.tsx
Labels: bug

#1327 [BED-5710] Update SH Foss version ref to 2.6.2
  dockerfiles/bloodhound.Dockerfile
Labels: bug

#1324 BED-5640: BHCE Resources V2 Testing
  cmd/api/src/api/mocks/authenticator.go
  cmd/api/src/api/tools/analysis_schedule_test.go
  cmd/api/src/api/v2/ad_entity_test.go
  cmd/api/src/api/v2/ad_related_entity_test.go
  cmd/api/src/api/v2/analysisrequest_test.go
  cmd/api/src/api/v2/apiclient/mocks/credential.go
  cmd/api/src/api/v2/azure.go
  cmd/api/src/api/v2/azure_test.go
  cmd/api/src/api/v2/collectors_test.go
  cmd/api/src/api/v2/cypherquery_test.go
  cmd/api/src/api/v2/dataquality_test.go
  cmd/api/src/api/v2/edge_test.go
  cmd/api/src/api/v2/file_uploads_test.go
  cmd/api/src/api/v2/helpers_test.go
  cmd/api/src/daemons/datapipe/mocks/cleanup.go
  cmd/api/src/database/mocks/auth.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/go.mod
  cmd/api/src/go.sum
  cmd/api/src/queries/mocks/graph.go
  cmd/api/src/services/agi/mocks/mock.go
  cmd/api/src/services/dataquality/mocks/mock.go
  cmd/api/src/utils/test/response.go
  cmd/api/src/utils/validation/mocks/validator.go
  cmd/api/src/vendormocks/io/fs/mock.go
Labels: api

#1336 BED-5714 Small Bug Fix in St Bernard Package
  packages/go/stbernard/main.go
Labels: tooling

#1289 BHE-5639 Integration Test Removal (preparation for replacement)
  cmd/api/src/api/v2/analysisrequest_integration_test.go
  cmd/api/src/api/v2/app_config_integration_test.go
  cmd/api/src/api/v2/audit_integration_test.go
  cmd/api/src/api/v2/auth/auth_integration_test.go
  cmd/api/src/api/v2/azure_integration_test.go
  cmd/api/src/api/v2/cypherquery_integration_test.go
  cmd/api/src/api/v2/datapipe_integration_test.go
  cmd/api/src/api/v2/file_uploads_integration_test.go
  cmd/api/src/auth/role_test.go
Labels: api

#1331 [BED-4714] Correct filename embedded into image
  dockerfiles/bloodhound.Dockerfile
  tools/docker-compose/api.Dockerfile
Labels: bug, infrastructure

#1344 BED-5457: Link to Explore from Attack Path Findings
  packages/javascript/bh-shared-ui/src/hooks/useGraphItem.tsx
  packages/javascript/bh-shared-ui/src/utils/parseItemId.ts
  packages/javascript/bh-shared-ui/src/utils/searchParams/searchParams.ts
Labels: user interface

#1335 feat: BED-5468 - added a graph fixture loader for graph json files
  cmd/api/src/analysis/ad/ad_integration_test.go
  cmd/api/src/test/integration/graph.go
  cmd/api/src/test/integration/harnesses.go
  cmd/api/src/test/integration/harnesses/completenessharness.json
  cmd/api/src/test/integration/harnesses/completenessharness.svg
  local-harnesses/build.config.json.template
  packages/go/lab/loader.go
Labels: enhancement, api, tooling

#1330 BED-5693: Create an RFC template for use as a starting point when creating an RFC
  rfc/rfc-template.md
Labels: documentation

#1356 fix: finish upgrading x/crypto
  cmd/api/src/go.mod
  cmd/api/src/go.sum
  packages/go/analysis/go.mod
  packages/go/bhlog/go.mod
  packages/go/bomenc/go.mod
  packages/go/bomenc/go.sum
  packages/go/conftool/go.mod
  packages/go/crypto/go.mod
  packages/go/crypto/go.sum
  packages/go/cypher/go.mod
  packages/go/cypher/go.sum
  packages/go/dawgs/go.mod
  packages/go/dawgs/go.sum
  packages/go/ein/go.mod
  packages/go/schemagen/go.mod
  packages/go/schemagen/go.sum
  packages/go/stbernard/go.mod
Labels: bug

#1357 chore: remove tests from just prepare-for-codereview
  justfile
Labels: work in progress, tooling

#1361 BED-5551: Clicking on node item in Edge Composition or Relay Targets panel performs single node search in explore
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC1/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10a/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC10b/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC3/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC6a/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC9a/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/ADCSESC9b/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToADCS/RelayTargets.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAP/RelayTargets.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToLDAPS/RelayTargets.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/CoerceAndRelayNTLMToSMB/RelaySources.tsx
  packages/javascript/bh-shared-ui/src/components/HelpTexts/GoldenCert/Composition.tsx
  packages/javascript/bh-shared-ui/src/components/VirtualizedNodeList.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useEdgeInfoItems.test.tsx
  packages/javascript/bh-shared-ui/src/hooks/useExploreGraph/useEdgeInfoItems.ts
Labels: user interface

#1338 BED-5271: Tiering delete selector
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/api/v2/assetgrouptags_test.go
  cmd/api/src/database/assetgrouptags.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/model/audit.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.selectors.id.yaml
Labels: enhancement, api

#1367 BED-5764: Relationship search / Graph rendering only happening if member count under query limit
  cmd/ui/src/views/Explore/EntityInfo/EntityInfoDataTable.tsx
Labels: bug, user interface

#1373 chore: update DoodleUI and browserlist
  .yarn/cache/@bloodhoundenterprise-doodleui-npm-1.0.0-alpha.16-dea67b5e37-91f3843fc9.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001597-1e349680d5-ec6a2cf0fd.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001692-6af96beb31-484113e3fa.zip
  .yarn/cache/caniuse-lite-npm-1.0.30001714-c8999c91f0-e68fbee9a1.zip
  cmd/ui/package.json
  yarn.lock
Labels: enhancement, user interface

#1213 BED-5249: feat: Get Tier/Label List Endpoint
  cmd/api/src/api/constant.go
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/v2/ad_entity.go
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/api/v2/assetgrouptags_test.go
  cmd/api/src/api/v2/azure.go
  cmd/api/src/database/assetgrouptags.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/mocks/db.go
  cmd/api/src/model/assetgrouptags.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.yaml
  packages/go/openapi/src/schemas/api.params.predicate.filter.integer-strict.yaml
  packages/go/openapi/src/schemas/api.params.predicate.filter.string-strict.yaml
Labels: enhancement, api

#1368 BED-5759: feat: add email column to AssetGroupHistory and related methods
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/database/assetgrouphistory.go
  cmd/api/src/database/assetgrouphistory_test.go
  cmd/api/src/database/assetgrouptags.go
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/migration/migrations/v7.4.0.sql
  cmd/api/src/database/mocks/db.go
  cmd/api/src/model/assetgrouphistory.go
Labels: enhancement, api

#1364 BED-5622: NTLM GA
  cmd/api/src/database/migration/migrations/v7.3.0.sql
Labels: api

#1374 chore: bump sharphound versions for release
  dockerfiles/bloodhound.Dockerfile
  tools/docker-compose/api.Dockerfile
Labels: api

#1376 BED-5765: Preserve `environmentId` query param through links
  cmd/ui/src/components/MainNav/MainNavData.tsx
  cmd/ui/src/components/SettingsMenu.tsx
  cmd/ui/src/views/DisabledUser.tsx
  cmd/ui/src/views/EarlyAccessFeatures/EarlyAccessFeatures.tsx
  cmd/ui/src/views/Explore/utils.test.ts
  cmd/ui/src/views/GroupManagement/GroupManagement.tsx
  packages/javascript/bh-shared-ui/src/utils/searchParams/AppLink.tsx
  packages/javascript/bh-shared-ui/src/utils/searchParams/index.ts
  packages/javascript/bh-shared-ui/src/utils/searchParams/searchParams.ts
  packages/javascript/bh-shared-ui/src/utils/searchParams/useAppNavigate.ts
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.tsx
Labels: bug, user interface

#1379 feat(ui): enhance not-found page
  cmd/ui/src/views/DisabledUser.tsx
  cmd/ui/src/views/NotFound.tsx
Labels: enhancement, user interface

#1387 BED-5810 - Make stbernard Less Aggressive during Golang Code Generation
  packages/go/stbernard/workspace/golang/generate.go
  packages/go/stbernard/workspace/golang/mod.go
Labels: tooling

#1388 BED-5548: chore: migrate group management selectors
  cmd/api/src/database/assetgrouptags_test.go
  cmd/api/src/database/migration/migrations/v7.4.0.sql
Labels: api

#1392 BED-4563 - Number string presented as dates in entity panel
  packages/go/graphschema/ad/ad.go
  packages/go/graphschema/azure/azure.go
  packages/go/graphschema/common/common.go
  packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.test.ts
  packages/javascript/bh-shared-ui/src/utils/entityInfoDisplay.ts
Labels: bug, user interface

#1351 BED-5480: API-Task - List All Objects from Tier/Label
  cmd/api/src/api/registration/v2.go
  cmd/api/src/api/sort.go
  cmd/api/src/api/sort_test.go
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/api/v2/assetgrouptags_test.go
  cmd/api/src/api/v2/search.go
  cmd/api/src/api/v2/search_internal_test.go
  cmd/api/src/api/v2/search_test.go
  cmd/api/src/model/search.go
  cmd/api/src/model/search_test.go
  cmd/api/src/queries/graph.go
  cmd/api/src/queries/mocks/graph.go
  packages/go/analysis/azure/post_test.go
  packages/go/cypher/models/pgsql/format/format.go
  packages/go/cypher/models/pgsql/model.go
  packages/go/cypher/models/pgsql/test/translation_cases/multipart.sql
  packages/go/cypher/models/pgsql/test/translation_cases/nodes.sql
  packages/go/cypher/models/pgsql/translate/model.go
  packages/go/cypher/models/pgsql/translate/projection.go
  packages/go/cypher/models/pgsql/translate/renamer.go
  packages/go/cypher/models/pgsql/translate/translator.go
  packages/go/cypher/models/walk/walk_pgsql.go
  packages/go/dawgs/drivers/neo4j/node.go
  packages/go/dawgs/drivers/pg/node.go
  packages/go/dawgs/drivers/pg/node_test.go
  packages/go/dawgs/graph/mocks/query.go
  packages/go/dawgs/graph/query.go
  packages/go/dawgs/query/neo4j/neo4j_test.go
  packages/go/dawgs/query/sort.go
  packages/go/openapi/doc/openapi.json
  packages/go/openapi/src/openapi.yaml
  packages/go/openapi/src/paths/asset-isolation.asset-group-tags.id.members.yaml
Labels: documentation, enhancement, api

#1409 Revert "BHE-5639 Integration Test Removal (preparation for replacement)"
  cmd/api/src/api/v2/analysisrequest_integration_test.go
  cmd/api/src/api/v2/app_config_integration_test.go
  cmd/api/src/api/v2/audit_integration_test.go
  cmd/api/src/api/v2/auth/auth_integration_test.go
  cmd/api/src/api/v2/azure_integration_test.go
  cmd/api/src/api/v2/cypherquery_integration_test.go
  cmd/api/src/api/v2/datapipe_integration_test.go
  cmd/api/src/api/v2/file_uploads_integration_test.go
  cmd/api/src/auth/role_test.go
Labels: api

#1408 BED-5816 (chore) adding tests for GetEdgeRelayTargets & changing TestVersion_730_Migration to integration test
  cmd/api/src/api/v2/edge_test.go
  cmd/api/src/migrations/migrations_integration_test.go
Labels: api

#1401 BED-5535 Updated permissions to be checked in order to interact with database management component
  cmd/ui/src/views/DatabaseManagement/DatabaseManagement.test.tsx
  cmd/ui/src/views/DatabaseManagement/DatabaseManagement.tsx
  packages/javascript/bh-shared-ui/src/utils/permissions.ts
Labels: bug, user interface

#1414 feat: BED-5761
  cmd/ui/package.json
  cmd/ui/vite.config.ts
  packages/javascript/bh-shared-ui/package.json
  packages/javascript/bh-shared-ui/rollup.config.js
  packages/javascript/bh-shared-ui/src/views/TierManagement/Details/Details.tsx
  yarn.lock
Labels: enhancement, user interface

#1418 Bed 5737
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/model/filter.go
  cmd/api/src/model/filter_internal_test.go
  cmd/api/src/model/saved_queries.go
Labels: api

#1427 Revert "Bed 5737"
  cmd/api/src/api/v2/assetgrouptags.go
  cmd/api/src/model/filter.go
  cmd/api/src/model/filter_internal_test.go
  cmd/api/src/model/saved_queries.go
Labels: api
